"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { organizationRepository, visitProgramRepository, visitRequestRepository } from "@/lib/action-opportunities/browser-repository";
import type { AdoptionSnapshot, SchoolDirectorySnapshot, ShelterNeedsSnapshot, ShelterStatsSnapshot } from "@/lib/government-open-data";
import { DATA_SOURCE_LAYER_LABELS, ORGANIZATION_TYPE_LABELS, TAIWAN_COUNTIES, type ActionOrganization, type OrganizationMatch } from "@/lib/action-opportunities/types";
import { matchActionOrganizations } from "@/lib/action-opportunities/repository";
import styles from "./teacher-local-resources.module.css";

const ResourceMap=dynamic(()=>import("@/app/student/week/[week]/_components/week-six-action-map"),{ssr:false,loading:()=> <div className={styles.mapFallback}>正在整理動保資源地圖…</div>});
type SearchScope="same_district"|"same_county"|"cross_county";
const EMPTY_PROFILE={age:18,county:"",weeklyTime:"1_2" as const,participationModes:[],travelAbility:"cross_county" as const,skills:[],commitment:"both" as const,adultSupport:"confirmed" as const,preferredRole:"information" as const};

const json=<T,>(url:string,signal:AbortSignal)=>fetch(url,{signal}).then(response=>{if(!response.ok)throw new Error(`${url}: ${response.status}`);return response.json() as Promise<T>});

export default function TeacherLocalResources(){
  const [county,setCounty]=useState("臺北市"),[schoolId,setSchoolId]=useState(""),[scope,setScope]=useState<SearchScope>("same_county"),[selectedId,setSelectedId]=useState("");
  const [visitOrganizationId,setVisitOrganizationId]=useState(""),[visitDate,setVisitDate]=useState(""),[visitCount,setVisitCount]=useState(30),[visitNote,setVisitNote]=useState("希望安排高中班級參訪，認識動保工作與安全參與方式。"),[visitMessage,setVisitMessage]=useState("");
  const [adoptions,setAdoptions]=useState<AdoptionSnapshot|null>(null),[stats,setStats]=useState<ShelterStatsSnapshot|null>(null),[needs,setNeeds]=useState<ShelterNeedsSnapshot|null>(null),[schools,setSchools]=useState<SchoolDirectorySnapshot|null>(null),[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();Promise.all([json<AdoptionSnapshot>("/api/open-data/adoptions",controller.signal),json<ShelterStatsSnapshot>("/api/open-data/shelter-stats",controller.signal),json<ShelterNeedsSnapshot>("/api/open-data/shelter-needs",controller.signal),json<SchoolDirectorySnapshot>("/api/open-data/schools",controller.signal)]).then(([a,s,n,sc])=>{setAdoptions(a);setStats(s);setNeeds(n);setSchools(sc)}).catch(()=>{if(!controller.signal.aborted)setError("目前無法載入資料。請稍後重試；系統不會用示範資料冒充政府資料。")});return()=>controller.abort()},[]);
  const countySchools=useMemo(()=>schools?.schools.filter(school=>school.county===county)??[],[schools,county]);
  const selectedSchool=schools?.schools.find(school=>school.id===schoolId);
  const allMatches=useMemo(()=>matchActionOrganizations(adoptions?.organizations??[],{...EMPTY_PROFILE,county}),[adoptions,county]);
  const matches=useMemo(()=>scope==="cross_county"?allMatches:allMatches.filter(match=>match.organization.county===county),[allMatches,county,scope]);
  const selected=matches.find(match=>match.organization.id===selectedId)?.organization??matches[0]?.organization;
  const need=needs?.latestByCounty.find(row=>row.county===county),stat=stats?.latestByCounty.find(row=>row.county===county);
  const count=(value:number|null|undefined)=>value===null||value===undefined?"資料未提供":value.toLocaleString("zh-TW");
  const handleCounty=(value:string)=>{setCounty(value);setSchoolId("");setSelectedId("")};
  const partnerOrganizations=organizationRepository.partnerManaged();
  const submitVisitRequest=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),organizationId=String(form.get("organizationId")||visitOrganizationId||partnerOrganizations[0]?.id||""),requestedDate=String(form.get("requestedDate")||visitDate),participantCount=Number(form.get("participantCount")||visitCount),note=String(form.get("note")||visitNote);if(!organizationId){setVisitMessage("目前沒有可接收站內參訪需求的功能展示單位。");return}const program=visitProgramRepository.forOrganization(organizationId).find(item=>item.status==="published")??visitProgramRepository.ensureDemoForOrganization(organizationId);if(!program){setVisitMessage("此單位目前沒有公開的參訪方案。");return}const request=visitRequestRepository.create({visitProgramId:program.id,organizationId,studentId:"local-demo-teacher",requesterRole:"teacher",requestedDate:requestedDate||program.availableDates[0]||"待協調",participantCount,note});setVisitMessage(request?"已送出功能展示參訪需求；同一瀏覽器中的對應動保夥伴可在工作台查看。":"參訪需求未建立，請確認單位與方案資料。")};
  return <main className={styles.page}><nav><Link href="/teacher/questions">← 返回教師端</Link><span>Week 6 教師工具</span></nav><header><p>學校與在地資源</p><h1>從學校所在縣市規劃動保行動</h1><p>先用教育部名錄選擇學校，再檢視同縣市的官方資源與收容需求。未取得可靠座標時，本頁不宣稱真實公里距離。</p></header>
    <section className={styles.controls}><label>縣市<select value={county} onChange={event=>handleCounty(event.target.value)}>{TAIWAN_COUNTIES.map(item=><option key={item}>{item}</option>)}</select></label><label>學校<select value={schoolId} onChange={event=>setSchoolId(event.target.value)}><option value="">選擇學校</option>{countySchools.map(school=><option key={school.id} value={school.id}>{school.name}</option>)}</select></label><label>搜尋層級<select value={scope} onChange={event=>setScope(event.target.value as SearchScope)}><option value="same_district" disabled>同區（目前缺少可靠行政區／座標）</option><option value="same_county">同縣市</option><option value="cross_county">跨縣市資料比較</option></select></label>{selectedSchool&&<p><strong>{selectedSchool.name}</strong><br/>{selectedSchool.county} · {selectedSchool.address}</p>}{schools&&<div className={styles.sourceMeta}><strong>{schools.source.mode==="live"?"政府開放資料":"政府資料備援快照"}</strong><span>提供機關：教育部統計處</span><span>資料期間：{schools.source.updatedAt}</span><a href={schools.source.datasetUrl} target="_blank" rel="noreferrer">查看高中名錄原始資料 ↗</a><small>這筆資料只決定學校所在縣市與同縣市篩選，不產生公里距離。</small></div>}</section>
    {error&&<p role="alert" className={styles.error}>{error}</p>}
    <section className={styles.grid}><div><ResourceMap matches={matches as OrganizationMatch[]} location={null} selectedId={selected?.id??""} onSelect={setSelectedId}/><p className={styles.mapNote}>{scope==="same_county"?`目前只顯示 ${county} 的動保資源。`:`目前顯示跨縣市資料供課程比較；不代表這些單位位於學校附近。`} 地圖座標來自單位資料，學校名錄未提供座標，因此未計算距離。</p></div><aside className={styles.summary}><span>政府開放資料</span><h2>{county}收容需求摘要</h2><div><article><small>月底在養數</small><strong>{count(need?.currentTotal)}</strong></article><article><small>可留容動物最大值</small><strong>{count(need?.maxCapacity)}</strong></article><article><small>當月合計入所</small><strong>{count(need?.totalIntake)}</strong></article><article><small>最近一期認領養</small><strong>{count(stat?.adoptedCount)}</strong></article></div><p>統計期間：表二 {needs?.source.updatedAt??"載入中"}；認領養統計 {stats?.source.updatedAt??"載入中"}。</p><p>這些數字只用來設計查證問題與課程討論，不做縣市好壞排名，也不推論志工名額。</p><div className={styles.sources}><a href="https://data.gov.tw/dataset/41236" target="_blank" rel="noreferrer">收容處理統計 ↗</a><a href="https://data.nat.gov.tw/dataset/73396" target="_blank" rel="noreferrer">收容處理統計表二 ↗</a><a href="https://data.gov.tw/dataset/6089" target="_blank" rel="noreferrer">高中名錄 ↗</a></div></aside></section>
    <section className={styles.resources}><h2>{scope==="same_county"?`${county}動保資源`:`跨縣市動保資源比較`}</h2>{!adoptions&&!error&&<p>正在讀取政府資料…</p>}{matches.slice(0,12).map(({organization})=><ResourceCard key={organization.id} organization={organization} selected={selected?.id===organization.id} onSelect={()=>setSelectedId(organization.id)}/>)}</section>
    <section className={styles.controls}><h2>提出團體參訪需求</h2><p><strong>功能展示資料：</strong>只會送到同一瀏覽器的動保夥伴工作台，不代表已向真實單位預約。</p><form className={styles.visitForm} onSubmit={submitVisitRequest}><label>接收需求的展示單位<select aria-label="參訪接收單位" name="organizationId" value={visitOrganizationId} onChange={event=>setVisitOrganizationId(event.target.value)}><option value="">選擇展示單位</option>{partnerOrganizations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>希望日期<input aria-label="參訪希望日期" name="requestedDate" type="date" value={visitDate} onChange={event=>setVisitDate(event.target.value)}/></label><label>參與人數<input aria-label="參訪人數" name="participantCount" type="number" min="1" value={visitCount} onChange={event=>setVisitCount(Number(event.target.value))}/></label><label>課程與安全需求<textarea aria-label="參訪需求說明" name="note" value={visitNote} onChange={event=>setVisitNote(event.target.value)}/></label><button type="submit">送出功能展示參訪需求</button>{visitMessage&&<p role="status">{visitMessage}</p>}</form></section>
  </main>;
}

function ResourceCard({organization,selected,onSelect}:{organization:ActionOrganization;selected:boolean;onSelect:()=>void}){return <article data-selected={selected}><div><span>{DATA_SOURCE_LAYER_LABELS[organization.sourceLayer]}</span><span>{ORGANIZATION_TYPE_LABELS[organization.organizationType]}</span></div><h3>{organization.name}</h3><p>{organization.county} · {organization.address}</p><p>{organization.phone}</p><p>查核日期：{organization.verifiedAt}</p><p><strong>資料如何影響顯示：</strong>縣市決定同縣市篩選；單位類型與公開標籤只供教學規劃，不代表目前有志工名額。</p><div><button type="button" onClick={onSelect}>在地圖查看</button><a href={organization.sourceUrl} target="_blank" rel="noreferrer">查看原始資料 ↗</a></div></article>}
