import { type ResourceCategoryFilter, type ActionFilter, type ActionOrganization, type PreferredRole, type ActionProfile, type Coordinates, type OrganizationMatch, type ContactMethod, type WeekSixJourneyDraft, type WeekSixLegacyDraft, DEFAULT_ACTION_PROFILE, DEFAULT_ACTION_RECORD, SAFETY_SCENARIOS } from "./types";

export function createWeekSixDraft():WeekSixJourneyDraft { return { version:2, stage:0, furthestStage:0, profile:{...DEFAULT_ACTION_PROFILE}, selectedSchoolId:"", resourceCategoryFilter:"all", actionFilter:"all", selectedOrganizationId:"", comparisonOrganizationIds:[], safetyAnswers:{}, contactMethod:"phone", contactDrafts:{phone:"",email:"",visit_proposal:"",school_proposal:""}, actionRecord:{...DEFAULT_ACTION_RECORD}, updatedAt:new Date().toISOString(), status:"draft", openDataDate:"" }; }

export function requiredComparisonCount(availableCount:number){return Math.min(2,Math.max(0,Math.floor(availableCount)));}
export function areSafetyAnswersCorrect(answers:Record<string,string>){return SAFETY_SCENARIOS.every(s=>answers[s.id]===s.answer);}

export function filterActionMatches(matches:OrganizationMatch[],category:ResourceCategoryFilter,action:ActionFilter){
  return matches.filter(({organization})=>{
    const categoryMatches=category==="all"
      ||(category==="government"&&["public_shelter","animal_home","government_agency","education_park"].includes(organization.organizationType))
      ||(category==="public_care"&&["public_shelter","animal_home"].includes(organization.organizationType))
      ||(category==="education_park"&&organization.organizationType==="education_park")
      ||(category==="registered_nonprofit"&&organization.organizationType==="registered_nonprofit")
      ||(category==="rescue_group"&&organization.organizationType==="rescue_group")
      ||(category==="partner_managed"&&organization.managementMode==="partner_managed")
      ||(category==="internal_application"&&organization.managementMode==="partner_managed")
      ||(category==="visit"&&organization.actionTags.includes("visit"))
      ||(category==="volunteer"&&organization.hasOfficialVolunteerInfo)
      ||(category==="school_outreach"&&organization.actionTags.includes("school_outreach"));
    const actionMatches=action==="all"||organization.actionTags.includes(action);
    return categoryMatches&&actionMatches;
  });
}

export function normalizeCountyName(value:string){return value.trim().replace(/^台/,"臺").replace(/台([北中南東])/,"臺$1");}
function organizationIdentity(value:string){return value.normalize("NFKC").toLowerCase().replace(/[\s　()（）·．。、-]/g,"");}
function organizationIdOrder(value:string){const parsed=Number(value.replace(/\D/g,""));return Number.isFinite(parsed)?parsed:0;}
const SUPERSEDED_ORGANIZATION_IDS=new Set(["PS00000017"]);
export function dedupeActionOrganizations(organizations:ActionOrganization[]):ActionOrganization[]{const deduped=new Map<string,ActionOrganization>();for(const organization of organizations){if(SUPERSEDED_ORGANIZATION_IDS.has(organization.id))continue;const key=`${normalizeCountyName(organization.county)}|${organizationIdentity(organization.name)}`,existing=deduped.get(key);if(!existing){deduped.set(key,organization);continue}const preferred=organizationIdOrder(organization.id)>organizationIdOrder(existing.id)?organization:existing,fallback=preferred===organization?existing:organization;deduped.set(key,{...fallback,...preferred,openingHours:preferred.openingHours||fallback.openingHours,officialUrl:preferred.officialUrl||fallback.officialUrl,officialServices:preferred.officialServices?.length?preferred.officialServices:fallback.officialServices,openDogCount:Math.max(preferred.openDogCount??0,fallback.openDogCount??0)});}return[...deduped.values()];}
export function haversineDistanceKm(from:Coordinates,to:Coordinates){const r=6371,rad=(n:number)=>n*Math.PI/180,dLat=rad(to.latitude-from.latitude),dLon=rad(to.longitude-from.longitude);const a=Math.sin(dLat/2)**2+Math.cos(rad(from.latitude))*Math.cos(rad(to.latitude))*Math.sin(dLon/2)**2;return r*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function minorEligibility(age:number,o:ActionOrganization){if(age>=18)return{eligible:true,reason:"年齡符合成人參與條件"};if(o.minorPolicy==="adult_only"||(o.minimumAge??0)>=18)return{eligible:false,reason:"目前不符合直接參與資格"};if(o.minorPolicy==="guardian_required")return{eligible:true,reason:"需由家長或監護人同意／陪同"};if(o.minorPolicy==="teacher_group_only")return{eligible:true,reason:"需由教師以團體方式聯絡"};return{eligible:true,reason:o.minorPolicy==="allowed"?"資料標示未成年可參與":"未成年參與規定需先向單位確認"};}
export function matchActionOrganizations(organizations:ActionOrganization[],profile:ActionProfile,location?:Coordinates|null):OrganizationMatch[]{const county=normalizeCountyName(profile.county);return organizations.map(o=>{const minor=minorEligibility(profile.age,o),sameCounty=!county||normalizeCountyName(o.county)===county,publishedModes=o.participationModes.length>0,modeMatch=!publishedModes||profile.participationModes.length===0||profile.participationModes.some(m=>o.participationModes.includes(m)),publishedCommitment=o.commitmentTypes.length>0,commitmentMatch=!publishedCommitment||profile.commitment==="both"||o.commitmentTypes.includes(profile.commitment),travelMatch=profile.travelAbility==="cross_county"||profile.travelAbility==="guardian_accompanied"||(profile.travelAbility==="online_only"?(!publishedModes||o.participationModes.includes("online")):sameCounty),distanceKm=location?haversineDistanceKm(location,o):null,reasons=[minor.reason];if(sameCounty)reasons.push("位於所選縣市");if(!publishedModes)reasons.push("參與方式尚待向單位確認");if(profile.age<18&&profile.adultSupport==="confirmed")reasons.push("已有成人協助規劃聯絡");if(!travelMatch)reasons.push("超出目前交通條件");const exactMatch=minor.eligible&&sameCounty&&modeMatch&&commitmentMatch&&travelMatch,score=(minor.eligible?25:0)+(sameCounty?30:0)+(modeMatch?10:0)+(commitmentMatch?10:0)+(travelMatch?15:0)-(distanceKm??0)/100;return{organization:o,eligible:minor.eligible,exactMatch,reasons,distanceKm,score};}).sort((a,b)=>a.exactMatch===b.exactMatch?(location?(a.distanceKm??Infinity)-(b.distanceKm??Infinity):b.score-a.score):a.exactMatch?-1:1);}
function validProfile(value:unknown):ActionProfile{const p=value&&typeof value==="object"?value as Partial<ActionProfile>:{};return{...DEFAULT_ACTION_PROFILE,...p,adultSupport:p.adultSupport??DEFAULT_ACTION_PROFILE.adultSupport,preferredRole:p.preferredRole??DEFAULT_ACTION_PROFILE.preferredRole,participationModes:Array.isArray(p.participationModes)?p.participationModes:DEFAULT_ACTION_PROFILE.participationModes,skills:Array.isArray(p.skills)?p.skills:DEFAULT_ACTION_PROFILE.skills};}
export function parseWeekSixDraft(value:string|null):WeekSixJourneyDraft|null{if(!value)return null;try{const raw=JSON.parse(value) as Partial<WeekSixJourneyDraft>|Partial<WeekSixLegacyDraft>;if(raw.version===1&&raw.profile&&typeof raw.selectedOrganizationId==="string"){const d=createWeekSixDraft();return{...d,profile:validProfile(raw.profile),selectedOrganizationId:raw.selectedOrganizationId,comparisonOrganizationIds:raw.selectedOrganizationId?[raw.selectedOrganizationId]:[],openDataDate:raw.openDataDate??""};}if(raw.version!==2||!raw.profile||typeof raw.selectedOrganizationId!=="string")return null;const d=createWeekSixDraft();return{...d,...raw,profile:validProfile(raw.profile),stage:Math.max(0,Math.min(5,Number(raw.stage)||0)),furthestStage:Math.max(0,Math.min(5,Number(raw.furthestStage)||0)),comparisonOrganizationIds:Array.isArray(raw.comparisonOrganizationIds)?raw.comparisonOrganizationIds.filter((v):v is string=>typeof v==="string").slice(0,3):[],safetyAnswers:raw.safetyAnswers&&typeof raw.safetyAnswers==="object"?raw.safetyAnswers:{},contactDrafts:{...d.contactDrafts,...(raw.contactDrafts??{})},actionRecord:{...d.actionRecord,...(raw.actionRecord??{})}};}catch{return null;}}
export function roleSummary(p:ActionProfile){const roles:Record<PreferredRole,string>={information:"資料整理者",school_project:"宣導設計者",remote_support:"認養曝光協助者",onsite_learning:"參訪紀錄者",material_coordinator:"物資募集者",contact_proposer:"聯絡提案者",not_sure:"先詢問再決定"};const eligibility=p.age>=18?"仍需依單位規定確認參與資格":p.adultSupport==="confirmed"?"已有成人協助，仍需確認參與類型與最低年齡":"需先確認成人支持、參與類型與最低年齡";return`目前適合從「${roles[p.preferredRole]}」開始；${eligibility}，再依官方回覆調整行動。`;}
export function buildContactDrafts(o:ActionOrganization,p:ActionProfile):Record<ContactMethod,string>{const intro=`您好，我是關心動物議題的學生，想先了解 ${o.name} 目前公開且適合學生參與的需求。`,conditions=`我目前 ${p.age} 歲。請問這次參與屬於正式志工、學生服務學習、參訪，還是其他方式？最低年齡為何？是否需要家長或學校同意、成人陪同、事前訓練、保險、預約或固定服務時數？`;return{phone:`${intro}\n${conditions}\n我不會未經同意直接到場，謝謝您。`,email:`主旨：學生參與方式詢問\n\n${intro}\n${conditions}\n若目前沒有適合的方式，也想請教可查閱的官方資訊。謝謝。`,visit_proposal:`主旨：學生參訪 ${o.name} 申請草稿\n\n希望由教師或家長陪同，以生命教育與資料查證為目的進行參訪。\n預計先確認：可申請對象、人數、日期、導覽內容、年齡與安全規範、交通及影像紀錄限制。\n本草稿只供討論，將由負責成人確認後再使用官方管道提出申請。`,school_proposal:`提案主題：與 ${o.name} 建立安全的學生行動\n\n目的：先向官方單位確認真實需求，再由教師與學生評估可行方式。\n需確認：參與類型、最低年齡、家長或學校同意、成人陪同、訓練、保險、預約、交通、服務時段與內容。\n下一步：由教師或指定成人使用官方聯絡方式詢問，不直接承諾或到場。`};}
