import { z } from "zod";
import { assertSameOrigin, body, endpoint, RequestError } from "@/lib/classroom/http";
import { requireAccount } from "@/lib/classroom/auth";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
const schema=z.object({title:z.string().trim().min(2).max(120),summary:z.string().trim().max(300).default(""),description:z.string().trim().min(10).max(5000),activityType:z.string().trim().min(1).max(50),eventStartAt:z.string().datetime().optional(),eventEndAt:z.string().datetime().optional(),applicationDeadline:z.string().datetime().optional(),capacity:z.number().int().positive().max(10000).optional(),contactEmail:z.string().email().optional(),contactPhone:z.string().trim().max(40).optional(),publish:z.boolean().default(false)}).strict();
const statusSchema=z.object({id:z.string().uuid(),status:z.enum(["published","suspended","closed"])}).strict();
const deleteSchema=z.object({id:z.string().uuid()}).strict();
export async function GET(request:Request){return endpoint(async()=>{if(new URL(request.url).searchParams.get("student")==="1"){await requireAccount("student");const supabase=createAdminSupabaseClient();const {data,error}=await supabase.from("shelter_volunteer_activities").select("id,shelter_id,title,summary,description,activity_type,event_start_at,event_end_at,application_deadline,capacity,contact_email,contact_phone,status,created_at,updated_at,shelters(name,address,contact_email)").eq("status","published").order("updated_at",{ascending:false});if(error)throw new RequestError(500,"目前無法載入收容所活動公告。");return{activities:data??[],syncedAt:new Date().toISOString()};}const account=await requireAccount("shelter"),supabase=await createServerSupabaseClient("shelter");const {data:binding,error:bindingError}=await supabase.from("shelter_accounts").select("shelter_id,shelters(name,address,contact_email)").eq("user_id",account.id).single();if(bindingError||!binding)throw new RequestError(403,"帳號尚未綁定收容所。");const {data:activities,error}=await supabase.from("shelter_volunteer_activities").select("id,shelter_id,title,summary,description,activity_type,event_start_at,event_end_at,application_deadline,capacity,contact_email,contact_phone,status,created_at,updated_at").eq("shelter_id",binding.shelter_id).order("updated_at",{ascending:false});if(error)throw new RequestError(500,"目前無法讀取活動資料。");return{shelter:{id:binding.shelter_id,...(binding.shelters as unknown as {name:string;address:string;contact_email:string})},activities:activities??[]};});}
export async function POST(request:Request){return endpoint(async()=>{assertSameOrigin(request);const account=await requireAccount("shelter"),input=await body(request,schema),supabase=await createServerSupabaseClient("shelter");const {data:binding}=await supabase.from("shelter_accounts").select("shelter_id,shelters(name)").eq("user_id",account.id).single();if(!binding)throw new RequestError(403,"帳號尚未綁定收容所。");const {data,error}=await supabase.from("shelter_volunteer_activities").insert({shelter_id:binding.shelter_id,created_by:account.id,title:input.title,summary:input.summary,description:input.description,activity_type:input.activityType,event_start_at:input.eventStartAt,event_end_at:input.eventEndAt,application_deadline:input.applicationDeadline,capacity:input.capacity,contact_email:input.contactEmail,contact_phone:input.contactPhone,status:input.publish?"published":"draft"}).select("id,shelter_id,status").single();if(error)throw new RequestError(400,"活動儲存失敗，請檢查欄位。");return{activity:data,shelterName:(binding.shelters as unknown as {name?:string})?.name??""};});}
export async function PATCH(request:Request){return endpoint(async()=>{assertSameOrigin(request);const account=await requireAccount("shelter"),input=await body(request,statusSchema),supabase=await createServerSupabaseClient("shelter");const {data:binding}=await supabase.from("shelter_accounts").select("shelter_id").eq("user_id",account.id).single();if(!binding)throw new RequestError(403,"帳號尚未綁定收容所。");const {data,error}=await supabase.from("shelter_volunteer_activities").update({status:input.status}).eq("id",input.id).eq("shelter_id",binding.shelter_id).select("id,status").single();if(error||!data)throw new RequestError(400,"活動狀態更新失敗。");return{activity:data};});}
export async function DELETE(request:Request){return endpoint(async()=>{assertSameOrigin(request);const account=await requireAccount("shelter"),input=await body(request,deleteSchema),supabase=await createServerSupabaseClient("shelter");const {data:binding}=await supabase.from("shelter_accounts").select("shelter_id").eq("user_id",account.id).single();if(!binding)throw new RequestError(403,"帳號尚未綁定收容所。");const {data,error}=await supabase.from("shelter_volunteer_activities").delete().eq("id",input.id).eq("shelter_id",binding.shelter_id).select("id").single();if(error||!data)throw new RequestError(400,"活動刪除失敗。");return{deletedId:data.id};});}
