"use client";
import { useEffect, useMemo, useState } from "react";
import { sprint3BehaviorCodes } from "@/lib/observations/session-engine";

export default function ObservationClient() {
  const [remaining, setRemaining] = useState(300);
  const [events, setEvents] = useState<Array<{ code: string; second: number }>>([{ code: "LOOK_AT_HUMAN", second: 12 }, { code: "SIT", second: 30 }]);
  useEffect(() => { const timer = window.setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, []);
  const display = useMemo(() => `${String(Math.floor(remaining / 60)).padStart(2, "0")}:${String(remaining % 60).padStart(2, "0")}`, [remaining]);
  return <main className="mx-auto max-w-6xl p-5 lg:p-8"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-4"><div><p className="text-xs font-semibold text-cyan-700">SYNTHETIC_DEMO · SL-OBS-1 · non-contact</p><h1 className="mt-1 text-2xl font-semibold">Observation Timer</h1><p className="mt-2 text-sm text-slate-600">Biscuit · GREEN_OBSERVATION · server deadline 300 seconds</p></div><div className="text-right"><div aria-label="Observation timer" className="font-mono text-5xl font-semibold tabular-nums">{display}</div><p className="mt-1 text-xs text-slate-500">Server time is authoritative</p></div></header><progress aria-label="Observation progress" className="mt-4 h-3 w-full" max={300} value={300 - remaining} /><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section><h2 className="text-lg font-semibold">Behavior Buttons</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{sprint3BehaviorCodes.map((code) => <button className="min-h-12 border bg-white p-2 text-sm font-medium hover:border-cyan-600" key={code} type="button" aria-label={`Record ${code}`} onClick={() => setEvents((current) => [...current, { code, second: 300 - remaining }])}>{code}</button>)}</div></section><section className="border-l border-slate-200 pl-5"><h2 className="text-lg font-semibold">Timeline</h2><ol className="mt-3 divide-y border-y text-sm">{events.map((event, index) => <li className="grid grid-cols-[58px_1fr] py-2" key={`${event.code}-${index}`}><span className="font-mono text-slate-500">{String(Math.floor(event.second / 60)).padStart(2, "0")}:{String(event.second % 60).padStart(2, "0")}</span><span>{event.code} · confidence required</span></li>)}</ol><dl className="mt-5 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-500">Setting</dt><dd>Indoor</dd></div><div><dt className="text-slate-500">Distance</dt><dd>2–5 m</dd></div><div><dt className="text-slate-500">Barrier</dt><dd>Kennel gate</dd></div><div><dt className="text-slate-500">Staff</dt><dd>Present</dd></div></dl></section></div><a className="mt-7 inline-block border border-slate-400 bg-white px-4 py-2 text-sm font-medium" href="/observations/review">Review Before Submit</a></main>;
}
