"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { api, buttonClass, fieldClass } from "@/app/_components/classroom-ui";
import CaseComparison from "@/app/_components/case-comparison";
import DataLens from "@/app/_components/data-lens";
import type { QuestionSet, SubmittedAnswer } from "@/lib/classroom/data-types";
type Work = { status: string; version: number; generation: number; questionSet: QuestionSet; answers: SubmittedAnswer[] | null; feedback: string };
export default function WeekSubmission({ week }: { week: number }) {
  const [work, setWork] = useState<Work | null>(null), [answers, setAnswers] = useState<SubmittedAnswer[]>([]), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; api<Work>(`/api/classroom/weeks/${week}`).then(w => { if (!active) return; setWork(w); setAnswers(w.answers || w.questionSet.questions.map(q => ({ questionId: q.id, text: "", selectedAnimalIds: [] }))); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [week]);
  const readOnly = work?.status !== "in_progress";
  return <section id="classroom-submission" className="relative z-10 mx-auto my-10 max-w-6xl space-y-6 rounded-3xl border border-teal-200 bg-[#faf8f3] p-5 sm:p-8"><Link className="underline" href="/student">← 返回學習地圖</Link><h1 className="text-3xl font-bold">第 {week} 週 · 資料探究與送審</h1><p>觀察下列真實資料快照，展開資料透鏡，再逐題回答與選擇引用個案。送出後等待教師批改，不會自行解鎖下一週。</p><p role="alert" className="text-red-800">{error}</p>{work ? <><p role="status" className="rounded-xl bg-teal-100 p-4 font-bold">{work.status === "pending" ? "等待審核中：作答已送出，下一週仍鎖定。" : work.status === "completed" ? "已完成：教師已通過本週作業。返回地圖查看下一週。" : "進行中：請逐題作答並選擇引用紀錄。"}</p>{work.feedback && <p className="rounded-xl bg-amber-50 p-4">教師回饋：{work.feedback}</p>}<CaseComparison set={work.questionSet} /><form className="space-y-6" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); try { await api(`/api/classroom/weeks/${week}`, { version: work.version, generation: work.generation, answers }); setWork(await api<Work>(`/api/classroom/weeks/${week}`)); window.dispatchEvent(new Event("classroom-progress")); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>
    {work.questionSet.questions.map((q, i) => <fieldset key={q.id} disabled={readOnly || busy} className="rounded-2xl border bg-white p-5"><legend className="px-2 text-lg font-bold">第 {i + 1} 題</legend><p className="text-sm text-stone-600">{q.fact}</p><label className="mt-3 block font-bold" htmlFor={q.id}>{q.prompt}</label><textarea id={q.id} required minLength={10} maxLength={3000} rows={5} className={fieldClass} value={answers[i]?.text || ""} onChange={e => setAnswers(current => current.map((a, index) => index === i ? { ...a, text: e.target.value } : a))} /><p className="my-3 text-sm">引用哪些個案？{q.id === "compare" ? "比較題至少選兩個" : "至少選一個"}。</p><div className="flex flex-wrap gap-4">{work.questionSet.cases.map(a => <label key={a.id} className="flex items-center gap-2"><input type="checkbox" checked={answers[i]?.selectedAnimalIds.includes(a.id) || false} onChange={e => setAnswers(current => current.map((answer, index) => index === i ? { ...answer, selectedAnimalIds: e.target.checked ? [...answer.selectedAnimalIds, a.id] : answer.selectedAnimalIds.filter(id => id !== a.id) } : answer))} />{a.id} · {a.colour}</label>)}</div></fieldset>)}
    <DataLens metadata={work.questionSet.metadata} /><p className="text-sm">題目資料由後端計算；{work.questionSet.wordingSource === "constrained_ai" ? "AI 僅選用受限制的高中問句，未產生任何數字。" : "目前使用高中引導問句範本，未啟用 AI。"}</p><button disabled={readOnly || busy || work.questionSet.cases.length < 2} className={buttonClass}>{busy ? "送出中…" : "送出作答，等待教師審核"}</button>
    </form></> : !error && <p>正在載入資料題目…</p>}</section>;
}
