"use client";

import Link from "next/link";
import { type FormEvent, useMemo, useState } from "react";
import { organizationRegistrationRepository, organizationRepository } from "@/lib/action-opportunities/browser-repository";
import { ORGANIZATION_TYPE_LABELS, TAIWAN_COUNTIES, type OrganizationType } from "@/lib/action-opportunities/types";
import styles from "../../action-opportunity-console.module.css";

const selectableTypes:OrganizationType[]=["public_shelter","animal_home","animal_protection_office","animal_welfare_education_park","private_rescue_group","animal_welfare_association","foundation","other_verified_organization"];

export default function OrganizationRegistrationPage(){
  const [county,setCounty]=useState(""),[type,setType]=useState<OrganizationType>("public_shelter"),[organizationId,setOrganizationId]=useState(""),[newRequest,setNewRequest]=useState(false),[submitted,setSubmitted]=useState(false);
  const organizations=useMemo(()=>organizationRepository.list().filter(item=>(!county||item.county===county)&&(!type||item.organizationType===type||type==="animal_protection_office"&&item.organizationType==="government_agency"||type==="animal_welfare_education_park"&&item.organizationType==="education_park"||type==="private_rescue_group"&&item.organizationType==="rescue_group")),[county,type]);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),selected=organizationRepository.get(organizationId);organizationRegistrationRepository.submit({organizationId:newRequest?undefined:organizationId||undefined,requestedOrganizationName:newRequest?String(form.get("organizationName")||""):undefined,organizationType:type,county,address:newRequest?String(form.get("address")||""):selected?.address,officialWebsite:newRequest?String(form.get("website")||""):selected?.officialUrl,publicPhone:String(form.get("phone")||""),officialEmail:String(form.get("email")||""),sourceUrl:newRequest?String(form.get("sourceUrl")||""):selected?.sourceUrl,contactName:String(form.get("contactName")||""),contactTitle:String(form.get("contactTitle")||""),isNewOrganizationRequest:newRequest});setSubmitted(true)};
  if(submitted)return <main className={styles.workspace}><section className={styles.workspaceMain}><section className={styles.heroPanel}><div><p>機構確認申請</p><h1>等待平台確認</h1><p>申請已保存在這台瀏覽器的展示資料中。平台尚未完成正式驗證，也沒有建立可冒用機構身分的帳號；狀態確認為 verified 前不能發布活動。</p></div><Link className={styles.primary} href="/shelter">返回動保機構端</Link></section></section></main>;
  return <main className={styles.workspace}><section className={styles.workspaceMain}><header className={styles.workspaceHeader}><div><p>ShelterLab Prototype</p><h1>動保機構註冊與身分確認</h1><span className={styles.demoPill}>尚未連接正式驗證後端</span></div><Link href="/shelter">返回工作台</Link></header><section className={styles.panel}><h2>先綁定公開機構名錄，再由平台確認代表身分</h2><p>公開名錄出現某個單位，不代表任何人可以立刻以該單位身分刊登活動。</p><form className={styles.form} onSubmit={submit}><label>縣市<select required value={county} onChange={event=>{setCounty(event.target.value);setOrganizationId("")}}><option value="">請選擇縣市</option>{TAIWAN_COUNTIES.map(value=><option key={value}>{value}</option>)}</select></label><label>機構類型<select value={type} onChange={event=>{setType(event.target.value as OrganizationType);setOrganizationId("")}}>{selectableTypes.map(value=><option key={value} value={value}>{ORGANIZATION_TYPE_LABELS[value]}</option>)}</select></label>{!newRequest&&<label className={styles.full}>既有機構名錄<select aria-label="選擇既有機構" required value={organizationId} onChange={event=>setOrganizationId(event.target.value)}><option value="">搜尋結果：請選擇正確機構</option>{organizations.map(item=><option key={item.id} value={item.id}>{item.name}｜{item.address}</option>)}</select></label>}<label className={styles.full}><input type="checkbox" checked={newRequest} onChange={event=>{setNewRequest(event.target.checked);setOrganizationId("")}}/>找不到我的機構／申請新增機構</label>{newRequest&&<><label>機構正式名稱<input required name="organizationName"/></label><label>地址<input required name="address"/></label><label>官方網站或正式社群頁面<input required type="url" name="website"/></label><label>資料來源網址<input required type="url" name="sourceUrl"/></label></>}<label>申請人姓名<input required name="contactName"/></label><label>職稱<input required name="contactTitle"/></label><label>官方 Email<input required type="email" name="email"/></label><label>官方電話<input required name="phone"/></label><button className={styles.primary}>送出機構確認申請</button></form><p className={styles.notice}>送出後狀態為 pending。這個前端展示不會寄信或完成真實身分驗證，也不會讓待確認單位發布活動。</p></section></section></main>;
}
