"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ACTION_DATA_EVENT, applicationRepository, invitationRepository, notificationRepository, opportunityRepository, organizationRepository, studentActionProfileRepository, visitProgramRepository, visitRequestRepository } from "@/lib/action-opportunities/browser-repository";
import { APPLICATION_STATUS_LABELS, type ActionNotification, type MatchInvitation, type NotificationCategory, type OpportunityApplication, type VisitRequest } from "@/lib/action-opportunities/types";
import styles from "./inbox.module.css";

const categoryLabels:Record<NotificationCategory|"all",string>={all:"全部類型",new_opportunity:"新機會",application:"申請進度",organization:"單位通知",visit:"參訪通知",reminder:"提醒",system:"系統",saved:"收藏提醒",matching:"媒合邀請"};
const visitLabels:Record<VisitRequest["status"],string>={submitted:"已送出",under_review:"確認中",needs_information:"待補資料",accepted:"已接受",reschedule_proposed:"建議改期",declined:"未接受",cancelled:"已取消",completed:"已完成"};

export default function ActionInboxPage(){
  const [items,setItems]=useState<ActionNotification[]>([]),[applications,setApplications]=useState<OpportunityApplication[]>([]),[invitations,setInvitations]=useState<MatchInvitation[]>([]),[visits,setVisits]=useState<VisitRequest[]>([]);
  const [category,setCategory]=useState<NotificationCategory|"all">("all"),[view,setView]=useState<"all"|"unread"|"read"|"saved">("all"),[message,setMessage]=useState("");
  const reload=()=>{const studentId=studentActionProfileRepository.get().studentId;setItems(notificationRepository.list());setApplications(applicationRepository.list().filter(item=>item.studentId===studentId));setInvitations(invitationRepository.forStudent(studentId));setVisits(visitRequestRepository.forStudent(studentId))};
  useEffect(()=>{reload();window.addEventListener(ACTION_DATA_EVENT,reload);return()=>window.removeEventListener(ACTION_DATA_EVENT,reload)},[]);
  const visible=useMemo(()=>items.filter(item=>{if(category!=="all"&&item.category!==category)return false;if(view==="unread"&&item.read)return false;if(view==="read"&&!item.read)return false;if(view==="saved"&&!item.saved)return false;return !item.archived}),[items,category,view]);
  const respond=(invitationId:string,response:"accepted"|"declined")=>{const result=invitationRepository.respond(invitationId,response);setMessage(response==="accepted"?(result?.applicationId?"你已接受邀請，系統已建立一筆正式申請。":"目前無法建立申請，請確認活動是否仍開放。 "):"你已婉拒這次邀請；不會建立申請。");reload()};
  return <main className={styles.page}>
    <header className={styles.header}><p>學生行動中心</p><h1>行動信箱</h1><p>查看媒合邀請、申請狀態、參訪回覆、集合資訊與安全提醒。匿名媒合只有在你接受邀請後，才會建立正式申請。</p><p className={styles.count}>目前有 {items.filter(item=>!item.read).length} 則未讀通知</p></header>
    <p className={styles.prototype}>Prototype：展示資料只儲存在這台瀏覽器，不會真的傳給外部單位。展示單位與活動均非真實合作或招募。</p>
    {message&&<p className={styles.prototype} role="status">{message}</p>}
    <section className={styles.controls} aria-label="通知篩選"><select aria-label="通知類型" value={category} onChange={e=>setCategory(e.target.value as NotificationCategory|"all")}>{Object.entries(categoryLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>{(["all","unread","read","saved"] as const).map(value=><button className={view===value?styles.primary:""} key={value} onClick={()=>setView(value)}>{value==="all"?"全部":value==="unread"?"未讀":value==="read"?"已讀":"已收藏"}</button>)}<button onClick={()=>{notificationRepository.markAllRead();reload()}}>全部標為已讀</button><Link href="/student/opportunities">回到活動布告欄</Link></section>

    <section className={styles.list}><h2>媒合邀請</h2>{invitations.map(invitation=>{const opportunity=opportunityRepository.get(invitation.opportunityId),organization=organizationRepository.get(invitation.organizationId);return <article className={styles.card} key={invitation.id}><span className={styles.dot}/><div><h2>{opportunity?.title}</h2><div className={styles.meta}><span className={styles.badge}>匿名媒合邀請</span><span>{organization?.name}</span><span>{invitation.status}</span></div><p className={styles.summary}>{invitation.message}</p></div><div className={styles.actions}>{invitation.status==="pending"?<><button onClick={()=>respond(invitation.id,"declined")}>婉拒邀請</button><button className={styles.primary} onClick={()=>respond(invitation.id,"accepted")}>接受並建立申請</button></>:<span>已回覆：{invitation.status==="accepted"?"接受":"婉拒"}</span>}</div></article>})}{invitations.length===0&&<p>目前沒有媒合邀請。</p>}</section>

    <section className={styles.list}><h2>我的申請</h2>{applications.map(application=>{const opportunity=opportunityRepository.get(application.opportunityId),organization=organizationRepository.get(application.organizationId);return <article className={styles.card} key={application.id}><span className={styles.dot}/><div><h2>{opportunity?.title}</h2><div className={styles.meta}><span className={styles.badge}>{application.kind==="direct_application"?"指定申請":"媒合後申請"}</span><span>{organization?.name}</span></div><p className={styles.summary}>目前狀態：{APPLICATION_STATUS_LABELS[application.status]}{application.serviceHours!==undefined?` · 已確認 ${application.serviceHours} 小時`:""}</p><details><summary>查看狀態歷程</summary><ol>{application.statusHistory.map((entry,index)=><li key={`${entry.changedAt}-${index}`}>{APPLICATION_STATUS_LABELS[entry.status]} · {entry.note||"無補充說明"}</li>)}</ol></details></div></article>})}{applications.length===0&&<p>目前沒有正式申請。</p>}</section>

    <section className={styles.list}><h2>參訪需求</h2>{visits.map(request=>{const program=visitProgramRepository.get(request.visitProgramId),organization=organizationRepository.get(request.organizationId);return <article className={styles.card} key={request.id}><span className={styles.dot}/><div><h2>{program?.title}</h2><div className={styles.meta}><span className={styles.badge}>{visitLabels[request.status]}</span><span>{organization?.name}</span></div><p className={styles.summary}>{request.participantCount} 人 · 希望日期 {request.requestedDate}{request.proposedDate?` · 建議日期 ${request.proposedDate}`:""}</p><p>{request.note}</p></div></article>})}{visits.length===0&&<p>目前沒有參訪需求。</p>}</section>

    <section className={styles.list} aria-live="polite"><h2>通知</h2>{visible.map(item=><article className={`${styles.card} ${item.read?styles.read:styles.unread}`} key={item.id}><span className={styles.dot}/><div><h2>{item.title}</h2><div className={styles.meta}><span className={styles.badge}>{categoryLabels[item.category]}</span><span>{item.source}</span><time dateTime={item.createdAt}>{new Intl.DateTimeFormat("zh-TW",{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.createdAt))}</time></div><p className={styles.summary}>{item.summary}</p></div><div className={styles.actions}><Link className={styles.primary} href={item.actionHref} onClick={()=>notificationRepository.markRead(item.id)}>{item.actionLabel}</Link><button onClick={()=>{notificationRepository.markRead(item.id,!item.read);reload()}}>{item.read?"標為未讀":"標為已讀"}</button><button onClick={()=>{notificationRepository.toggleSaved(item.id);reload()}}>{item.saved?"取消收藏":"收藏通知"}</button><button onClick={()=>{notificationRepository.archive(item.id);reload()}}>封存</button></div></article>)}{visible.length===0&&<div className={styles.empty}><h2>這個分類目前沒有通知</h2><p>你可以先到「活動布告欄」收藏或申請適合的活動。</p></div>}</section>
  </main>;
}
