"use client";
import { useEffect, useState } from "react";
import { api, buttonClass, fieldClass } from "@/app/_components/classroom-ui";
import type { schoolChoices, teacherDashboard } from "@/lib/classroom/service";
type Schools = Awaited<ReturnType<typeof schoolChoices>>;
type Dashboard = Awaited<ReturnType<typeof teacherDashboard>>;
export default function SettingsForm() {
  const [schools, setSchools] = useState<Schools | null>(null), [dashboard, setDashboard] = useState<Dashboard | null>(null), [schoolId, setSchoolId] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [studentId, setStudentId] = useState("");
  useEffect(() => { Promise.all([api<Schools>("/api/classroom/schools"), api<Dashboard>("/api/classroom/dashboard")]).then(([s, d]) => { setSchools(s); setDashboard(d); setSchoolId(d.classroom?.schoolId || ""); }).catch(e => setNotice(e.message)); }, []);
  const school = schools?.schools.find(s => s.id === schoolId);
  return <><p role="status" className="my-4 text-teal-900">{notice}</p>{!schools || !dashboard ? <p>正在載入學校與設定…</p> : <><form className="space-y-5 rounded-2xl border bg-white p-6" onSubmit={async e => { e.preventDefault(); setBusy(true); setNotice(""); const form = new FormData(e.currentTarget); try { await api("/api/classroom/settings", { schoolId, county: school?.county, grade: form.get("grade"), studentCount: Number(form.get("studentCount")), plannedWeeks: Number(form.get("plannedWeeks")) }); setDashboard(await api<Dashboard>("/api/classroom/dashboard")); setNotice("設定已儲存。工作台會自動載入在地資料。"); } catch (e) { setNotice((e as Error).message); } finally { setBusy(false); } }}>
    <label className="block">學校<select value={schoolId} onChange={e => setSchoolId(e.target.value)} required className={fieldClass}><option value="">請選擇學校</option>{schools.schools.map(s => <option key={s.id} value={s.id}>{s.county} · {s.name}</option>)}</select></label><p className="text-xs text-stone-500">{schools.source.message}。{schools.source.updatedAt}</p>
    <label className="block">縣市<input readOnly value={school?.county || ""} className={fieldClass} aria-describedby="county-note" /></label><p id="county-note" className="text-xs">由學校名錄鎖定，後端會再次核對。</p>
    <label className="block">年級<select name="grade" defaultValue={dashboard.classroom?.grade || "高一"} className={fieldClass}>{["高一", "高二", "高三"].map(g => <option key={g}>{g}</option>)}</select></label>
    <label className="block">班級人數<input type="number" name="studentCount" min={1} max={200} defaultValue={dashboard.classroom?.studentCount || 30} required className={fieldClass} /></label>
    <label className="block">預計進行週數<input type="number" name="plannedWeeks" min={1} max={6} defaultValue={dashboard.classroom?.plannedWeeks || 6} required className={fieldClass} /></label><p className="text-xs">本課程共有六週，可安排一至六週。有學生加入後固定學校與週數，維持作答資料一致。</p><button disabled={busy || !school} className={buttonClass}>{busy ? "儲存中…" : "儲存並載入在地設定"}</button>
  </form>{dashboard.classroom && <section className="mt-8 rounded-2xl border border-amber-300 bg-white p-6"><h2 className="text-xl font-bold">重設學生地圖解鎖進度</h2><p className="my-3">第一週恢復進行中，其餘關卡重新鎖定。已送出的作答會保留於稽核紀錄，不刪除學生帳號。</p><label className="block">選擇範圍<select value={studentId} onChange={e => setStudentId(e.target.value)} className={fieldClass}><option value="">全班學生</option>{dashboard.classroom.enrollments.map(e => <option key={e.student.id} value={e.student.id}>{e.student.displayName}</option>)}</select></label><button disabled={busy || dashboard.classroom.enrollments.length === 0} className="mt-4 rounded-xl border border-red-700 px-5 py-3 font-bold text-red-800 disabled:opacity-40" onClick={async () => { if (!window.confirm(`確定重設${studentId ? "所選學生" : "全班學生"}的地圖進度？`)) return; setBusy(true); try { const result = await api<{ resetCount: number }>("/api/classroom/reset", { confirmation: "RESET", ...(studentId ? { studentId } : {}) }); setNotice(`已重設 ${result.resetCount} 位學生的進度。`); } catch (e) { setNotice((e as Error).message); } finally { setBusy(false); } }}>重設進度</button></section>}</>}
  </>;
}
