import type { ImpactConfidenceLevel, ImpactEngineInput, ImpactEvidenceStatus, ImpactMetric, ImpactSnapshot, MetricProvenance, SdgMapping } from "./types";

const VERSION = "SL-IMPACT-1";
const round = (value: number) => Math.round(value * 100) / 100;
const uniqueCount = (values: string[]) => new Set(values).size;
const average = (values: number[]) => values.length === 0 ? 0 : round(values.reduce((sum, value) => sum + value, 0) / values.length);
const percent = (numerator: number, denominator: number) => denominator === 0 ? 0 : round((numerator / denominator) * 100);

function confidence(status: ImpactEvidenceStatus, denominator: number): ImpactConfidenceLevel {
  if (denominator === 0 || status === "UNVERIFIED") return "INSUFFICIENT";
  if (status === "SYNTHETIC") return "DEMO_ONLY";
  if (status === "DEMO") return "LOW";
  return "HIGH";
}

function source(sourceType: string, sourceId: string, sourceVersion: string, evidenceStatus: ImpactEvidenceStatus, label: string): MetricProvenance {
  return { sourceType, sourceId, sourceVersion, evidenceStatus, label };
}

function metric(input: Omit<ImpactMetric, "id" | "confidenceLevel" | "syntheticDemo" | "metricVersion">): ImpactMetric {
  return {
    ...input,
    id: `impact_${input.code.toLowerCase()}_${VERSION.toLowerCase()}`,
    confidenceLevel: confidence(input.evidenceStatus, input.denominator),
    syntheticDemo: input.evidenceStatus === "SYNTHETIC",
    metricVersion: VERSION
  };
}

export function calculateImpactSnapshot(input: ImpactEngineInput): ImpactSnapshot {
  const enrolled = input.learning.filter((item) => item.enrolled);
  const completed = enrolled.filter((item) => item.completed);
  const paired = enrolled.filter((item) => item.pretestScore !== undefined && item.posttestScore !== undefined);
  const pretestScores = enrolled.flatMap((item) => item.pretestScore === undefined ? [] : [item.pretestScore]);
  const posttestScores = enrolled.flatMap((item) => item.posttestScore === undefined ? [] : [item.posttestScore]);
  const learningGains = paired.map((item) => item.posttestScore! - item.pretestScore!);
  const licenseCompleted = enrolled.filter((item) => item.researchLicenseCompleted);
  const qualityGainTotal = input.qualityRevisions.reduce((sum, item) => sum + (item.latestScore - item.baselineScore), 0);
  const observedDogs = uniqueCount(input.observedDogIds);
  const approvedProfileDogs = uniqueCount(input.approvedProfileDogIds);
  const verifiedDatasets = uniqueCount(input.verifiedDatasetIds);
  const activeDatasets = uniqueCount(input.activeDatasetIds);
  const attributedDatasets = uniqueCount(input.attributedDatasetIds);
  const cohortSource = source("SyntheticLearningCohort", input.cohortId, "1", "SYNTHETIC", "Deterministic Sprint 8 learning cohort fixture");
  const livingLabSource = source("LivingLabDemoState", "sprint7-demo", "SL-OBS-1", "SYNTHETIC", "Sprint 7 immutable synthetic Living Lab state");
  const datasetSource = source("GovernmentDatasetRegistry", "sprint6.1-registry", "2026-07-11", "VERIFIED", "Verified official metadata and offline fixtures; no Sprint 8 network call");

  const metrics: ImpactMetric[] = [
    metric({ code: "STUDENTS_ENROLLED", domain: "EDUCATION", label: "Students enrolled", description: "Distinct synthetic learners in the demonstration cohort.", value: enrolled.length, unit: "count", formula: "COUNT(DISTINCT enrolled student_id)", numerator: enrolled.length, denominator: enrolled.length, evidenceStatus: "SYNTHETIC", provenance: [cohortSource], limitations: ["Synthetic cohort; not a real enrollment count."], calculatedAt: input.calculatedAt }),
    metric({ code: "LEARNING_COMPLETION_RATE", domain: "EDUCATION", label: "Learning completion rate", description: "Share of enrolled learners completing the synthetic learning sequence.", value: percent(completed.length, enrolled.length), unit: "percent", formula: "completed learners / enrolled learners * 100", numerator: completed.length, denominator: enrolled.length, evidenceStatus: "SYNTHETIC", provenance: [cohortSource], limitations: ["Completion does not prove learning transfer."], calculatedAt: input.calculatedAt }),
    metric({ code: "AVERAGE_PRETEST", domain: "EDUCATION", label: "Average pretest", description: "Mean available pretest score.", value: average(pretestScores), unit: "score", formula: "SUM(pretest scores) / learners with pretest", numerator: pretestScores.reduce((sum, value) => sum + value, 0), denominator: pretestScores.length, evidenceStatus: "SYNTHETIC", provenance: [cohortSource], limitations: ["Scores are deterministic fixtures."], calculatedAt: input.calculatedAt }),
    metric({ code: "AVERAGE_POSTTEST", domain: "EDUCATION", label: "Average posttest", description: "Mean available posttest score.", value: average(posttestScores), unit: "score", formula: "SUM(posttest scores) / learners with posttest", numerator: posttestScores.reduce((sum, value) => sum + value, 0), denominator: posttestScores.length, evidenceStatus: "SYNTHETIC", provenance: [cohortSource], limitations: ["Only learners with a posttest are included."], calculatedAt: input.calculatedAt }),
    metric({ code: "LEARNING_GAIN", domain: "EDUCATION", label: "Learning gain", description: "Mean paired posttest minus pretest change.", value: average(learningGains), unit: "percentage_points", formula: "SUM(posttest - pretest) / paired learners", numerator: learningGains.reduce((sum, value) => sum + value, 0), denominator: learningGains.length, evidenceStatus: "SYNTHETIC", provenance: [cohortSource], limitations: ["Descriptive paired change only; no control group or causal claim."], calculatedAt: input.calculatedAt }),
    metric({ code: "RESEARCH_LICENSE_COMPLETION", domain: "EDUCATION", label: "Research License completion", description: "Share of enrolled learners completing Research License qualification.", value: percent(licenseCompleted.length, enrolled.length), unit: "percent", formula: "learners completing license / enrolled learners * 100", numerator: licenseCompleted.length, denominator: enrolled.length, evidenceStatus: "SYNTHETIC", provenance: [cohortSource, source("ResearchLicense", "license_sprint7_demo_001", "1", "SYNTHETIC", "Active synthetic Research License proof")], limitations: ["Demo completion does not represent a school cohort."], calculatedAt: input.calculatedAt }),
    metric({ code: "OBSERVATION_MISSIONS", domain: "LIVING_LAB", label: "Observation missions", description: "Missions represented in the deterministic Living Lab state.", value: input.missionCount, unit: "count", formula: "COUNT(observation missions)", numerator: input.missionCount, denominator: input.missionCount, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Includes complete, revision, and available demonstration paths."], calculatedAt: input.calculatedAt }),
    metric({ code: "COMPLETED_MISSIONS", domain: "LIVING_LAB", label: "Completed missions", description: "Missions reaching separate manual publication.", value: input.completedMissionCount, unit: "count", formula: "COUNT(missions WHERE status = published)", numerator: input.completedMissionCount, denominator: input.missionCount, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Denominator provides all synthetic missions; value is the published mission count."], calculatedAt: input.calculatedAt }),
    metric({ code: "OBSERVATION_EVENTS", domain: "LIVING_LAB", label: "Observation events", description: "Structured behavior events retained in session versions.", value: input.observationEventCount, unit: "count", formula: "COUNT(behavior events across session versions)", numerator: input.observationEventCount, denominator: input.observationEventCount, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Revision versions may retain linked evidence; this is evidence volume, not unique behavior prevalence."], calculatedAt: input.calculatedAt }),
    metric({ code: "APPROVED_EVIDENCE", domain: "LIVING_LAB", label: "Approved evidence", description: "Current manually published evidence snapshots.", value: input.publishedEvidenceCount, unit: "count", formula: "COUNT(publications without unpublication)", numerator: input.publishedEvidenceCount, denominator: input.publishedEvidenceCount, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Approval indicates workflow governance, not clinical validity."], calculatedAt: input.calculatedAt }),
    metric({ code: "OBSERVATION_QUALITY", domain: "LIVING_LAB", label: "Observation quality", description: "Mean deterministic SL-OQS score for scored session versions.", value: average(input.observationQualityScores), unit: "score", formula: "SUM(SL-OQS scores) / scored sessions", numerator: input.observationQualityScores.reduce((sum, value) => sum + value, 0), denominator: input.observationQualityScores.length, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Review-priority score only; not dog temperament, welfare, or student grade."], calculatedAt: input.calculatedAt }),
    metric({ code: "DATA_QUALITY_IMPROVEMENT", domain: "LIVING_LAB", label: "Data quality improvement", description: "Mean score change from baseline to latest synthetic revision.", value: input.qualityRevisions.length === 0 ? 0 : round(qualityGainTotal / input.qualityRevisions.length), unit: "percentage_points", formula: "SUM(latest quality - baseline quality) / revised sessions", numerator: qualityGainTotal, denominator: input.qualityRevisions.length, evidenceStatus: "SYNTHETIC", provenance: [source("SyntheticRevisionEvaluation", "sprint8-quality-revisions", "1", "SYNTHETIC", "Deterministic before/after quality fixture")], limitations: ["Synthetic revision comparison; not a validated intervention effect."], calculatedAt: input.calculatedAt }),
    metric({ code: "DOGS_UPDATED", domain: "SHELTER", label: "Dogs updated", description: "Distinct observed dogs represented by updated evidence.", value: uniqueCount(input.updatedDogIds), unit: "count", formula: "COUNT(DISTINCT dogs with updated evidence)", numerator: uniqueCount(input.updatedDogIds), denominator: observedDogs, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Does not imply shelter database completeness."], calculatedAt: input.calculatedAt }),
    metric({ code: "EVIDENCE_COMPLETENESS", domain: "SHELTER", label: "Evidence completeness", description: "Observed dogs with approved profiles.", value: percent(approvedProfileDogs, observedDogs), unit: "percent", formula: "dogs with approved evidence profile / observed dogs * 100", numerator: approvedProfileDogs, denominator: observedDogs, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Small synthetic denominator; profile approval is not behavioral certainty."], calculatedAt: input.calculatedAt }),
    metric({ code: "PROFILE_COMPLETENESS", domain: "SHELTER", label: "Profile completeness", description: "Mean explicit completeness recorded on approved evidence profiles.", value: average(input.profileCompletenessScores), unit: "percent", formula: "SUM(profile completeness) / approved profiles", numerator: input.profileCompletenessScores.reduce((sum, value) => sum + value, 0), denominator: input.profileCompletenessScores.length, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Unknown information remains unknown and lowers completeness."], calculatedAt: input.calculatedAt }),
    metric({ code: "SHELTER_PARTICIPATION", domain: "SHELTER", label: "Shelter participation", description: "Eligible synthetic shelters represented in reviewed evidence.", value: percent(uniqueCount(input.engagedShelterIds), uniqueCount(input.eligibleShelterIds)), unit: "percent", formula: "engaged shelters / eligible shelters * 100", numerator: uniqueCount(input.engagedShelterIds), denominator: uniqueCount(input.eligibleShelterIds), evidenceStatus: "SYNTHETIC", provenance: [source("SyntheticPartnerCohort", "sprint8-partners", "1", "SYNTHETIC", "Deterministic partner fixture")], limitations: ["No real partner participation claim."], calculatedAt: input.calculatedAt }),
    metric({ code: "ADOPTION_SUPPORT_READINESS", domain: "ADOPTION_SUPPORT", label: "Adoption support readiness", description: "Observed dogs with a shelter-approved evidence profile available for future adoption support.", value: percent(approvedProfileDogs, observedDogs), unit: "percent", formula: "dogs with approved evidence profile / observed dogs * 100", numerator: approvedProfileDogs, denominator: observedDogs, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Readiness only; no inquiry, adoption, retention, or causal outcome is implemented."], calculatedAt: input.calculatedAt }),
    metric({ code: "TEACHER_ENGAGEMENT", domain: "SOCIAL", label: "Teacher engagement", description: "Eligible synthetic teachers participating in mission or review evidence.", value: percent(uniqueCount(input.engagedTeacherIds), uniqueCount(input.eligibleTeacherIds)), unit: "percent", formula: "engaged teachers / eligible teachers * 100", numerator: uniqueCount(input.engagedTeacherIds), denominator: uniqueCount(input.eligibleTeacherIds), evidenceStatus: "SYNTHETIC", provenance: [source("SyntheticPartnerCohort", "sprint8-partners", "1", "SYNTHETIC", "Deterministic partner fixture")], limitations: ["No real teacher adoption or satisfaction claim."], calculatedAt: input.calculatedAt }),
    metric({ code: "STUDENTS_ENGAGED", domain: "SOCIAL", label: "Students engaged", description: "Distinct synthetic learners represented in the impact cohort.", value: enrolled.length, unit: "count", formula: "COUNT(DISTINCT engaged synthetic student_id)", numerator: enrolled.length, denominator: enrolled.length, evidenceStatus: "SYNTHETIC", provenance: [cohortSource], limitations: ["Synthetic demonstration participants only."], calculatedAt: input.calculatedAt }),
    metric({ code: "TEACHERS_ENGAGED", domain: "SOCIAL", label: "Teachers engaged", description: "Distinct synthetic teachers represented in mission/review evidence.", value: uniqueCount(input.engagedTeacherIds), unit: "count", formula: "COUNT(DISTINCT engaged synthetic teacher_id)", numerator: uniqueCount(input.engagedTeacherIds), denominator: uniqueCount(input.eligibleTeacherIds), evidenceStatus: "SYNTHETIC", provenance: [source("SyntheticPartnerCohort", "sprint8-partners", "1", "SYNTHETIC", "Deterministic partner fixture")], limitations: ["No real teacher participation claim."], calculatedAt: input.calculatedAt }),
    metric({ code: "SHELTERS_ENGAGED", domain: "SOCIAL", label: "Shelters engaged", description: "Distinct synthetic shelters represented in reviewed evidence.", value: uniqueCount(input.engagedShelterIds), unit: "count", formula: "COUNT(DISTINCT engaged synthetic shelter_id)", numerator: uniqueCount(input.engagedShelterIds), denominator: uniqueCount(input.eligibleShelterIds), evidenceStatus: "SYNTHETIC", provenance: [source("SyntheticPartnerCohort", "sprint8-partners", "1", "SYNTHETIC", "Deterministic partner fixture")], limitations: ["No real shelter partnership claim."], calculatedAt: input.calculatedAt }),
    metric({ code: "COMMUNITY_PARTICIPATION", domain: "SOCIAL", label: "Community participation", description: "Distinct synthetic community participants represented in the impact fixture.", value: uniqueCount(input.communityParticipantIds), unit: "count", formula: "COUNT(DISTINCT synthetic community participant IDs)", numerator: uniqueCount(input.communityParticipantIds), denominator: uniqueCount(input.communityParticipantIds), evidenceStatus: "SYNTHETIC", provenance: [source("SyntheticCommunityCohort", "sprint8-community", "1", "SYNTHETIC", "Competition-only community fixture")], limitations: ["No foster, outing, adopter, or real community workflow is claimed."], calculatedAt: input.calculatedAt }),
    metric({ code: "VERIFIED_DATASETS", domain: "GOVERNMENT_OPEN_DATA", label: "Verified datasets", description: "Official dataset records passing the approved Sprint 6.1 verification checklist.", value: verifiedDatasets, unit: "count", formula: "COUNT(DISTINCT dataset_id WHERE verification_state = VERIFIED)", numerator: verifiedDatasets, denominator: verifiedDatasets, evidenceStatus: "VERIFIED", provenance: [datasetSource], limitations: ["Verification applies to recorded source metadata/fixture evidence, not a Sprint 8 live API call."], calculatedAt: input.calculatedAt }),
    metric({ code: "DATASET_USAGE", domain: "GOVERNMENT_OPEN_DATA", label: "Dataset usage", description: "Verified datasets active in an approved product use.", value: activeDatasets, unit: "count", formula: "COUNT(DISTINCT active verified dataset_id)", numerator: activeDatasets, denominator: verifiedDatasets, evidenceStatus: "VERIFIED", provenance: [datasetSource], limitations: ["Denominator provides the verified registry; inactive records are intentionally excluded from product use."], calculatedAt: input.calculatedAt }),
    metric({ code: "DATASET_ATTRIBUTION", domain: "GOVERNMENT_OPEN_DATA", label: "Dataset attribution coverage", description: "Active datasets carrying required attribution.", value: percent(attributedDatasets, activeDatasets), unit: "percent", formula: "active datasets with attribution / active datasets * 100", numerator: attributedDatasets, denominator: activeDatasets, evidenceStatus: "VERIFIED", provenance: [datasetSource], limitations: ["Attribution coverage does not replace license compliance review."], calculatedAt: input.calculatedAt }),
    metric({ code: "EVIDENCE_TRACEABILITY", domain: "GOVERNMENT_OPEN_DATA", label: "Evidence traceability", description: "Evidence-chain nodes reachable in the deterministic trace.", value: percent(input.tracedEvidenceChainNodeCount, input.evidenceChainNodeCount), unit: "percent", formula: "traceable evidence nodes / required evidence nodes * 100", numerator: input.tracedEvidenceChainNodeCount, denominator: input.evidenceChainNodeCount, evidenceStatus: "DEMO", provenance: [source("CompetitionEvidenceChain", "sprint6-to-sprint7", "1", "DEMO", "Read-only competition evidence trace")], limitations: ["Coverage describes implemented demo traceability, not production database durability."], calculatedAt: input.calculatedAt }),
    metric({ code: "ONE_HEALTH_HUMAN", domain: "ONE_HEALTH", label: "One Health: human", description: "Synthetic learner completion as the human/education indicator.", value: percent(completed.length, enrolled.length), unit: "percent", formula: "completed learners / enrolled learners * 100", numerator: completed.length, denominator: enrolled.length, evidenceStatus: "SYNTHETIC", provenance: [cohortSource], limitations: ["Education participation indicator, not a human-health outcome."], calculatedAt: input.calculatedAt }),
    metric({ code: "ONE_HEALTH_ANIMAL", domain: "ONE_HEALTH", label: "One Health: animal", description: "Observed dogs with shelter-approved evidence profiles.", value: percent(approvedProfileDogs, observedDogs), unit: "percent", formula: "dogs with approved profile / observed dogs * 100", numerator: approvedProfileDogs, denominator: observedDogs, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Evidence coverage indicator, not a welfare or adoption effect."], calculatedAt: input.calculatedAt }),
    metric({ code: "ONE_HEALTH_ENVIRONMENT", domain: "ONE_HEALTH", label: "One Health: environment", description: "Completed missions carrying required structured environmental context.", value: percent(input.completedContextCount, input.completedMissionCount), unit: "percent", formula: "completed missions with structured context / completed missions * 100", numerator: input.completedContextCount, denominator: input.completedMissionCount, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Context documentation indicator, not an environmental outcome."], calculatedAt: input.calculatedAt }),
    metric({ code: "EVIDENCE_GENERATED", domain: "SOCIAL", label: "Evidence generated", description: "Current published evidence snapshots plus approved profile statements.", value: input.publishedEvidenceCount + approvedProfileDogs, unit: "count", formula: "published evidence snapshots + approved dog evidence profiles", numerator: input.publishedEvidenceCount + approvedProfileDogs, denominator: input.publishedEvidenceCount + approvedProfileDogs, evidenceStatus: "SYNTHETIC", provenance: [livingLabSource], limitations: ["Counts evidence artifacts, not social impact outcomes."], calculatedAt: input.calculatedAt })
  ];

  const sdgMappings: SdgMapping[] = [
    { goal: "SDG 3", title: "Good Health and Well-being", contribution: "One Health literacy and responsible zoonotic-disease education.", metricCodes: ["ONE_HEALTH_HUMAN"], evidenceStatus: "SYNTHETIC", limitation: "No health outcome is measured." },
    { goal: "SDG 4", title: "Quality Education", contribution: "Research License learning, paired learning gain, and authentic scientific inquiry.", metricCodes: ["LEARNING_GAIN", "RESEARCH_LICENSE_COMPLETION"], evidenceStatus: "SYNTHETIC", limitation: "Demo cohort only; no causal evaluation." },
    { goal: "SDG 11", title: "Sustainable Cities and Communities", contribution: "Urban shelter evidence and community-facing public information.", metricCodes: ["COMMUNITY_PARTICIPATION", "EVIDENCE_GENERATED"], evidenceStatus: "SYNTHETIC", limitation: "No city-scale outcome is claimed." },
    { goal: "SDG 15", title: "Life on Land", contribution: "Structured animal observation and explicit environmental context.", metricCodes: ["ONE_HEALTH_ANIMAL", "ONE_HEALTH_ENVIRONMENT"], evidenceStatus: "SYNTHETIC", limitation: "No biodiversity or ecosystem effect is measured." },
    { goal: "SDG 17", title: "Partnerships for the Goals", contribution: "School, shelter, and verified government-data evidence chain.", metricCodes: ["TEACHER_ENGAGEMENT", "SHELTER_PARTICIPATION", "DATASET_USAGE"], evidenceStatus: "DEMO", limitation: "Partner participation is synthetic until field agreements exist." }
  ];

  return {
    id: `impact_snapshot_${input.cohortId}_${VERSION.toLowerCase()}`,
    version: VERSION,
    evidenceStatus: "SYNTHETIC",
    calculatedAt: input.calculatedAt,
    metrics,
    sdgMappings,
    warnings: [
      "Educational, shelter, adoption-support, social, and One Health outcomes are SYNTHETIC demonstration metrics.",
      "VERIFIED labels apply only to approved government source/fixture provenance, not real ShelterLab impact.",
      "All calculations are descriptive and deterministic; no AI generated or interpreted a metric."
    ]
  };
}

export function metricByCode(snapshot: ImpactSnapshot, code: string): ImpactMetric {
  const result = snapshot.metrics.find((item) => item.code === code);
  if (!result) throw new Error(`Impact metric ${code} not found.`);
  return result;
}
