import { describe, expect, it } from "vitest";
import { FALLBACK_ACTION_ORGANIZATIONS } from "@/data/action-organizations";
import { SAFETY_SCENARIOS, TAIWAN_COUNTIES, WEEK_SIX_DRAFT_KEY, type ActionProfile } from "@/lib/action-opportunities/types";
import { areSafetyAnswersCorrect, buildContactDrafts, createWeekSixDraft, filterActionMatches, haversineDistanceKm, matchActionOrganizations, parseWeekSixDraft, requiredComparisonCount, roleSummary } from "@/lib/action-opportunities/repository";
const profile:ActionProfile={age:16,county:"臺北市",weeklyTime:"1_2",participationModes:["online","onsite"],travelAbility:"within_county",skills:["recommend"],commitment:"both",adultSupport:"confirmed",preferredRole:"information"};
describe("Week 6 action journey",()=>{
 it("lists all 22 Taiwan counties",()=>expect(TAIWAN_COUNTIES).toHaveLength(22));
 it("keeps official shelters and marks unpublished participation rules",()=>{const results=matchActionOrganizations(FALLBACK_ACTION_ORGANIZATIONS,profile);expect(results.length).toBeGreaterThanOrEqual(30);expect(results[0].organization.county).toBe("臺北市");expect(results[0].reasons).toContain("未成年參與規定需先向單位確認");expect(results[0].organization.volunteerInformation).toBe("not_published")});
 it("does not hide adult-only services from minors",()=>{const adultOnly={...FALLBACK_ACTION_ORGANIZATIONS[0],id:"adult-only",minimumAge:18,minorPolicy:"adult_only" as const};const[result]=matchActionOrganizations([adultOnly],profile);expect(result.eligible).toBe(false);expect(result.exactMatch).toBe(false)});
 it("calculates Haversine distance",()=>{const d=haversineDistanceKm({latitude:25.033,longitude:121.5654},{latitude:24.1477,longitude:120.6736});expect(d).toBeGreaterThan(120);expect(d).toBeLessThan(150)});
 it("migrates v1 drafts without storing location",()=>{const legacy={version:1,profile:{...profile,adultSupport:undefined,preferredRole:undefined},selectedOrganizationId:"PS1",selectedAt:"2026-09-16T00:00:00.000Z",status:"draft",openDataDate:"2026-09-16"};const migrated=parseWeekSixDraft(JSON.stringify(legacy));expect(migrated?.version).toBe(2);expect(migrated?.selectedOrganizationId).toBe("PS1");expect(migrated?.profile.adultSupport).toBe("need_to_ask");expect(JSON.stringify(migrated)).not.toContain("latitude")});
 it("restores v2 and rejects invalid data",()=>{const draft={...createWeekSixDraft(),selectedOrganizationId:"PS1",stage:3,furthestStage:3};expect(parseWeekSixDraft(JSON.stringify(draft))?.stage).toBe(3);expect(parseWeekSixDraft("not-json")).toBeNull();expect(WEEK_SIX_DRAFT_KEY).toContain("v2")});
 it("creates four editable templates without sending anything",()=>{const drafts=buildContactDrafts(FALLBACK_ACTION_ORGANIZATIONS[0],profile);expect(drafts.phone).toContain("不會未經同意直接到場");expect(drafts.phone).toContain("學生服務學習");expect(drafts.phone).toContain("最低年齡");expect(drafts.email).toContain("主旨");expect(drafts.visit_proposal).toContain("參訪");expect(drafts.school_proposal).toContain("教師")});
 it("filters units separately from action methods",()=>{const results=matchActionOrganizations(FALLBACK_ACTION_ORGANIZATIONS,profile);expect(filterActionMatches(results,"education_park","all").every(result=>result.organization.organizationType==="education_park")).toBe(true);expect(filterActionMatches(results,"volunteer","volunteer").every(result=>result.organization.hasOfficialVolunteerInfo&&result.organization.actionTags.includes("volunteer"))).toBe(true)});
 it("includes verified education, administration and volunteer resources",()=>{expect(FALLBACK_ACTION_ORGANIZATIONS.some(item=>item.organizationType==="education_park")).toBe(true);expect(FALLBACK_ACTION_ORGANIZATIONS.some(item=>item.organizationType==="government_agency")).toBe(true);expect(FALLBACK_ACTION_ORGANIZATIONS.some(item=>item.hasOfficialVolunteerInfo)).toBe(true)});
 it("does not treat adult support as proof of minor eligibility",()=>{expect(roleSummary(profile)).toContain("仍需確認參與類型與最低年齡");expect(roleSummary({...profile,age:18})).toContain("仍需依單位規定確認參與資格")});
 it("adapts comparison requirements to the number of available organizations",()=>{expect(requiredComparisonCount(0)).toBe(0);expect(requiredComparisonCount(1)).toBe(1);expect(requiredComparisonCount(2)).toBe(2);expect(requiredComparisonCount(8)).toBe(2)});
 it("requires every safety answer to be correct and varies answer positions",()=>{const correct=Object.fromEntries(SAFETY_SCENARIOS.map(s=>[s.id,s.answer]));expect(areSafetyAnswersCorrect(correct)).toBe(true);expect(areSafetyAnswersCorrect(Object.fromEntries(SAFETY_SCENARIOS.map(s=>[s.id,s.options[0][0]])))).toBe(false);expect(new Set(SAFETY_SCENARIOS.map(s=>s.options.findIndex(([value])=>value===s.answer))).size).toBeGreaterThan(1)});
});
