import { z } from "zod";
import { analysisMethods, cleaningActionTypes, inquiryEvidenceTypes, inquiryTypes, oneHealthDimensions } from "./types";

export const projectCreateSchema=z.object({id:z.string().optional(),courseId:z.string().optional(),classroomId:z.string().optional(),researchGroupId:z.string().optional(),ownerStudentId:z.string(),supervisingTeacherId:z.string(),shelterId:z.string().optional(),title:z.string().trim().min(1),inquiryType:z.enum(inquiryTypes),oneHealthDimensions:z.array(z.enum(oneHealthDimensions)).min(2),oneHealthConnection:z.string().min(20),learningStandardIds:z.array(z.string()).min(1),researchQuestion:z.string().min(5),background:z.string().min(1),hypothesis:z.string().min(1),independentVariable:z.string().min(1),dependentVariable:z.string().min(1),controlledVariables:z.array(z.string()),evidenceScope:z.string().min(1),protocolVersion:z.string().default("SL-INQUIRY-1"),dataClassification:z.enum(["student_private","restricted_research","public_approved"]).default("student_private"),syntheticDemo:z.boolean().default(true),reflection:z.string().default("")});
export const projectPatchSchema=z.object({expectedRowVersion:z.number().int().nonnegative(),patch:z.object({title:z.string().optional(),oneHealthDimensions:z.array(z.enum(oneHealthDimensions)).min(2).optional(),oneHealthConnection:z.string().min(20).optional(),learningStandardIds:z.array(z.string()).min(1).optional(),researchQuestion:z.string().optional(),background:z.string().optional(),hypothesis:z.string().optional(),independentVariable:z.string().optional(),dependentVariable:z.string().optional(),controlledVariables:z.array(z.string()).optional(),evidenceScope:z.string().optional(),reflection:z.string().optional()})});
export const evidenceLinkSchema=z.object({evidenceType:z.enum(inquiryEvidenceTypes),sourceEntityId:z.string().min(1),sourceVersion:z.string().min(1),verificationState:z.enum(["VERIFIED","DEMO_REFERENCE","SYNTHETIC_DEMO","SHELTER_CONFIRMED","UNVERIFIED"]),usagePurpose:z.string().min(1),citationText:z.string().min(1),privacyClassification:z.enum(["public","restricted","private"])});
const variableSchema=z.object({name:z.string(),role:z.enum(["independent","dependent","controlled","context"]),unit:z.string().optional()});
export const researchDesignSchema=z.object({populationOrSample:z.string().min(1),observationUnit:z.string().min(1),samplingMethod:z.string().min(1),sampleSizePlanned:z.number().int().positive(),timePeriod:z.string().min(1),measurementMethod:z.string().min(1),variables:z.array(variableSchema).min(2),possibleConfounders:z.array(z.string()),ethicalLimits:z.string(),safetyLimits:z.string(),privacyLimits:z.string(),analysisPlan:z.string(),teacherDesignDecision:z.enum(["pending","approved","revision","rejected"]),teacherFeedback:z.string().optional()});
const cell=z.union([z.string(),z.number(),z.boolean(),z.null()]);
export const datasetSchema=z.object({id:z.string().optional(),name:z.string().min(1),columns:z.array(z.object({name:z.string(),unit:z.string().optional(),type:z.enum(["number","string","category","boolean"]),missingValueLabel:z.string().optional()})).min(1),rows:z.array(z.record(cell)),sourceProvenance:z.array(z.string()).min(1),syntheticDemo:z.boolean().default(true)});
export const transformationSchema=z.object({datasetId:z.string(),action:z.enum(cleaningActionTypes),column:z.string().optional(),fromValue:cell.optional(),toValue:cell.optional(),rowIndex:z.number().int().nonnegative().optional(),reason:z.string().optional(),formulaDescription:z.string().optional()});
const chartSchema=z.object({type:z.enum(["bar","line","stacked_bar","pie","histogram","scatterplot","table","one_health_system"]),title:z.string().min(1),xAxis:z.string().optional(),yAxis:z.string().optional(),categories:z.array(z.string()).optional(),unit:z.string().min(1),source:z.string().optional(),sampleSize:z.number().positive().optional(),evidenceLabel:z.enum(["VERIFIED","DEMO_REFERENCE","SYNTHETIC_DEMO"]),interpretationWarning:z.string().optional()});
export const analysisSchema=z.object({datasetVersionId:z.string(),method:z.enum(analysisMethods),variables:z.array(z.string()).min(1),filteredPopulation:z.string(),interpretationNote:z.string(),limitationNote:z.string().min(1),chart:chartSchema});
export const cerSchema=z.object({claim:z.string().min(1),evidenceLinkIds:z.array(z.string()).min(1),reasoning:z.string().min(1),confidenceLevel:z.enum(["low","medium","high"]),alternativeExplanation:z.string(),limitation:z.string().min(1),teacherFeedback:z.string().optional(),status:z.enum(["draft","submitted","revision","approved","rejected"])});
export const systemMapSchema=z.object({nodes:z.array(z.object({id:z.string(),type:z.enum(["student_community","shelter_staff","dogs","pathogen_parasite","environment","parks","rivers","waste_food","weather","schools","public_agencies","adoption_system"]),label:z.string(),evidenceLinkIds:z.array(z.string())})).min(2),edges:z.array(z.object({id:z.string(),fromNodeId:z.string(),toNodeId:z.string(),relationshipType:z.string(),direction:z.enum(["directed","bidirectional"]),evidenceLinkIds:z.array(z.string()).min(1),uncertainty:z.enum(["low","medium","high"]),impact:z.enum(["positive","negative","mixed","unknown"]),studentExplanation:z.string()})).min(1)});
export const recommendationSchema=z.object({recommendation:z.string(),targetActor:z.enum(["student","teacher","shelter","school","community","local_government"]),supportingEvidence:z.array(z.string()).min(1),feasibility:z.string(),expectedBenefit:z.string(),possibleRisk:z.string(),requiredResources:z.string(),evaluationIndicator:z.string(),studentScope:z.string(),status:z.enum(["proposed","teacher_approved","teacher_revision","shelter_confirmed","shelter_revision","rejected"]),evidenceStrength:z.enum(["limited","moderate","strong"])});
export const teacherReviewSchema=z.object({decision:z.enum(["approve","request_revision","reject"]),reason:z.string().optional(),rubric:z.record(z.number()).default({})});
export const shelterReviewSchema=z.object({decision:z.enum(["confirm","request_revision","reject"]),reason:z.string().optional()});

