import { shelterStatisticsFixture } from "../government-data/sprint6-fixtures";
import { InquiryService } from "./engine";
import type { InquiryActor, InquiryProject } from "./types";

export const inquiryDemoActors: Record<"student"|"teacher"|"shelter"|"admin",InquiryActor>={
  student:{id:"student_demo_001",role:"student"},teacher:{id:"teacher_demo_001",role:"teacher",authorizedCourseIds:["course_plan_shelterlab_16w_v1"],authorizedShelterIds:["SHELTER_TPE_001"]},
  shelter:{id:"shelter_staff_demo_001",role:"shelter_staff",authorizedShelterIds:["SHELTER_TPE_001"]},admin:{id:"admin_demo_001",role:"admin"}
};

const base=(id:string,title:string,type:InquiryProject["inquiryType"],dimensions:InquiryProject["oneHealthDimensions"],question:string):Parameters<InquiryService["createProject"]>[1]=>({
  id,courseId:"course_plan_shelterlab_16w_v1",classroomId:"classroom_synthetic_001",researchGroupId:"group_synthetic_one_health",ownerStudentId:inquiryDemoActors.student.id,supervisingTeacherId:inquiryDemoActors.teacher.id,
  title,inquiryType:type,oneHealthDimensions:dimensions,oneHealthConnection:"所選面向透過證據蒐集、解讀、教育與決策彼此連結，並持續清楚呈現未知。",learningStandardIds:["std_demo_data_interpretation"],
  researchQuestion:question,background:"使用核准證據與非因果科學推理的合成示範探究。",hypothesis:"同一報告期間的各縣市彙總資料可能呈現不同樣態。",independentVariable:"縣市",dependentVariable:"認養率",controlledVariables:["報告月份","紀錄定義"],evidenceScope:"只使用縣市月份彙總脈絡，不推論個別犬隻。",protocolVersion:"SL-INQUIRY-1",dataClassification:"student_private",syntheticDemo:true,reflection:"證據只支持有限比較與後續研究提問，不能形成因果結論。"
});

export function buildSprint9ADemo(){
  const service=new InquiryService();const {student,teacher,shelter}=inquiryDemoActors;const t=new Date("2026-07-13T01:00:00.000Z");
  const project=service.createProject(student,{...base("inquiry_synthetic_41236_complete","區域收容犬入所與認養率比較","shelter_statistics",["animal_welfare","environment","citizen_science","local_policy"],"同一彙總報告月份中，各縣市認養率摘要有何差異？"),shelterId:"SHELTER_TPE_001"},t).project;
  const datasetEvidence=service.linkEvidence(student,project.id,{evidenceType:"government_dataset_snapshot",sourceEntityId:"snapshot_41236_verified_fixture_20260711",sourceVersion:"41236-json-normalized-v1",verificationState:"VERIFIED",usagePurpose:"比較縣市月份入所數與認養率摘要。",citationText:"資料來源：農業部，全國公立動物收容所收容處理情形統計表（data.gov.tw 41236），已驗證離線快照。",privacyClassification:"public"},new Date("2026-07-13T01:01:00.000Z")).link;
  service.linkEvidence(student,project.id,{evidenceType:"learning_standard",sourceEntityId:"std_demo_data_interpretation",sourceVersion:"1",verificationState:"DEMO_REFERENCE",usagePurpose:"對應資料判讀能力。",citationText:"ShelterLab 示範參考（DEMO_REFERENCE）資料判讀標準，並非官方課綱代碼。",privacyClassification:"public"},new Date("2026-07-13T01:02:00.000Z"));
  service.linkEvidence(student,project.id,{evidenceType:"published_dog_evidence",sourceEntityId:"publication_session_mission_synthetic_biscuit_001_v1_1",sourceVersion:"session_mission_synthetic_biscuit_001_v1:v1",verificationState:"SHELTER_CONFIRMED",usagePurpose:"示範個別犬隻證據與彙總資料脈絡的界線。",citationText:"ShelterLab 合成示範資料（SYNTHETIC_DEMO）的已發布實境探究證據，不用於推論縣市結果。",privacyClassification:"restricted"},new Date("2026-07-13T01:03:00.000Z"));
  service.saveDesign(student,project.id,{populationOrSample:"四筆縣市月份彙總快照紀錄",observationUnit:"縣市月份紀錄",samplingMethod:"比較核准的驗證快照，不是隨機抽樣",sampleSizePlanned:4,timePeriod:"民國 115 年 5 月",measurementMethod:"依縣市比較認養率與入所數",variables:[{name:"縣市",role:"independent"},{name:"認養率",role:"dependent",unit:"百分比"},{name:"月份",role:"controlled"}],possibleConfounders:["通報方式","收容所量能","人口脈絡"],ethicalLimits:"不得排列人員優劣、診斷犬隻，或從單一比率推論動物福利。",safetyLimits:"不接觸動物，也不介入收容所營運。",privacyLimits:"只使用縣市彙總標示，不含犬隻或學生精確位置。",analysisPlan:"以長條圖比較縣市類別，並明確說明差異只屬描述性。",teacherDesignDecision:"approved",teacherFeedback:"只使用關聯或差異語句，不作因果解釋。"},new Date("2026-07-13T01:04:00.000Z"));
  const rows=shelterStatisticsFixture.rows.map(row=>({county:String(row.county),intake_count:Number(row.intakeCount),adopted_count:Number(row.adoptedCount),adoption_rate:Number(String(row.adoptionRate).replace("%","")),month:Number(row.month)}));
  const dataset=service.createDataset(student,project.id,{id:"inquiry_dataset_41236_county",name:"41236 縣市月份清理工作區",columns:[{name:"county",type:"category"},{name:"intake_count",type:"number",unit:"隻"},{name:"adopted_count",type:"number",unit:"隻"},{name:"adoption_rate",type:"number",unit:"百分比"},{name:"month",type:"number"}],rows:[...rows,cloneRow(rows[0])],sourceProvenance:[datasetEvidence.sourceEntityId],syntheticDemo:true},new Date("2026-07-13T01:05:00.000Z")).dataset;
  const cleaned=service.transformDataset(student,project.id,dataset.id,{action:"remove_duplicate",reason:"移除為固定清理示範刻意加入的完全重複資料。"},new Date("2026-07-13T01:06:00.000Z")).version;
  const analysis=service.addAnalysis(student,project.id,{datasetVersionId:cleaned.id,method:"regional_comparison",variables:["county","adoption_rate"],filteredPopulation:"民國 115 年 5 月快照紀錄",interpretationNote:"四個示範縣市的彙總認養率不同，但此樣態無法說明原因。",limitationNote:"只有四筆快照、一個月份、彙總定義，且沒有因果研究設計。",chart:{type:"bar",title:"縣市認養率比較",xAxis:"縣市",yAxis:"認養率",unit:"百分比",categories:rows.map(r=>String(r.county)),evidenceLabel:"VERIFIED",interpretationWarning:"這是彙總描述性比較，不得推論個別犬隻結果或收容所品質。"}},new Date("2026-07-13T01:07:00.000Z")).result;
  service.addCER(student,project.id,{claim:"四個驗證快照縣市摘要，在所選月份呈現不同認養率。",evidenceLinkIds:[datasetEvidence.id],reasoning:"同一期間的類別比較顯示官方彙總欄位有描述性差異；此比較支持差異主張，但不能解釋原因。",confidenceLevel:"medium",alternativeExplanation:"差異可能來自通報方式、人口、量能、入所組成或其他未量測因素。",limitation:"單一月份與四筆快照無法建立持續樣態或因果關係。",status:"submitted"},new Date("2026-07-13T01:08:00.000Z"));
  service.saveSystemMap(student,project.id,{nodes:[{id:"node_community",type:"student_community",label:"社區與學生",evidenceLinkIds:[datasetEvidence.id]},{id:"node_shelter",type:"shelter_staff",label:"公立動物收容所",evidenceLinkIds:[datasetEvidence.id]},{id:"node_dogs",type:"dogs",label:"收容犬族群摘要",evidenceLinkIds:[datasetEvidence.id]},{id:"node_policy",type:"public_agencies",label:"公部門機關",evidenceLinkIds:[datasetEvidence.id]}],edges:[{id:"edge_reporting",fromNodeId:"node_shelter",toNodeId:"node_policy",relationshipType:"彙總通報",direction:"directed",evidenceLinkIds:[datasetEvidence.id],uncertainty:"low",impact:"unknown",studentExplanation:"收容所提供彙總紀錄，形成公開脈絡。"},{id:"edge_learning",fromNodeId:"node_policy",toNodeId:"node_community",relationshipType:"開放資料學習",direction:"directed",evidenceLinkIds:[datasetEvidence.id],uncertainty:"medium",impact:"positive",studentExplanation:"在同步教導限制的前提下，已驗證彙總資料可支持資料素養探究。"}]},new Date("2026-07-13T01:09:00.000Z"));
  service.addRecommendation(student,project.id,{recommendation:"考慮改變收容所服務前，先進行跨月份且定義一致的後續研究。",targetActor:"shelter",supportingEvidence:[datasetEvidence.id,analysis.id],feasibility:"需要核准的每月彙總快照，以及教師與收容所審核。",expectedBenefit:"較能區分暫時波動與重複出現的樣態。",possibleRisk:"比率仍可能被誤讀為收容所排名。",requiredResources:"已驗證快照、欄位定義與審核時間",evaluationIndicator:"具有完整分母且可比較的月份數",studentScope:"學生可分析核准彙總資料並提出問題；收容所保留營運決定權。",status:"proposed",evidenceStrength:"limited"},new Date("2026-07-13T01:10:00.000Z"));
  service.submit(student,project.id,new Date("2026-07-13T01:11:00.000Z"));
  service.teacherReview(teacher,project.id,"approve",undefined,{research_question_formation:4,research_design:4,data_cleaning:4,data_interpretation:4,evidence_based_reasoning:4,one_health_understanding:4,scientific_communication:4,ethical_reasoning:4},new Date("2026-07-13T01:12:00.000Z"));
  service.shelterReview(shelter,project.id,"confirm",undefined,new Date("2026-07-13T01:13:00.000Z"));
  service.finalize(teacher,project.id,new Date("2026-07-13T01:14:00.000Z"));
  const demos=[
    base("inquiry_synthetic_40121_context","County education context inquiry","urban_ecology",["education","environment","local_policy"],"How do county student-population summaries differ across the verified fixture?"),
    {...base("inquiry_synthetic_behavior","Shelter behavior evidence inquiry","shelter_behavior",["animal_welfare","citizen_science","education"],"Which observable behavior codes appear in the published synthetic shelter session?"),shelterId:"SHELTER_TPE_001"},
    base("inquiry_synthetic_zoonosis","One Health prevention education inquiry","one_health_public_health",["human_health","animal_health","public_health","education"],"Which prevention concepts can students explain without diagnosing a person or animal?")
  ];
  for(const item of demos)service.createProject(student,item,new Date(t.getTime()+service.state.projects.size*60000));
  service.state.evidenceLinks.push({id:"evidence_40121_demo",projectId:"inquiry_synthetic_40121_context",evidenceType:"government_dataset_snapshot",sourceEntityId:"snapshot_40121_verified_fixture_20260711",sourceVersion:"40121-json-normalized-v1",verificationState:"VERIFIED",usagePurpose:"County education context",citationText:"資料來源：教育部統計處，各級學校縣市別學生人數（40121） verified fixture.",includedAt:t,includedBy:student.id,privacyClassification:"public"});
  service.state.evidenceLinks.push({id:"evidence_behavior_demo",projectId:"inquiry_synthetic_behavior",evidenceType:"published_dog_evidence",sourceEntityId:"publication_session_mission_synthetic_biscuit_001_v1_1",sourceVersion:"v1",verificationState:"SHELTER_CONFIRMED",usagePurpose:"Behavior frequency inquiry",citationText:"SYNTHETIC_DEMO shelter-confirmed evidence.",includedAt:t,includedBy:student.id,privacyClassification:"restricted"});
  service.state.evidenceLinks.push({id:"evidence_zoonosis_reference",projectId:"inquiry_synthetic_zoonosis",evidenceType:"teacher_reference",sourceEntityId:"teacher_reference_one_health_prevention_v1",sourceVersion:"1",verificationState:"DEMO_REFERENCE",usagePurpose:"Prevention-focused education without clinical claims",citationText:"Teacher-approved ShelterLab prevention reference; not clinical guidance.",includedAt:t,includedBy:teacher.id,privacyClassification:"public"});
  return service;
}

function cloneRow<T extends Record<string,unknown>>(row:T):T{return structuredClone(row);}
export const sprint9ADemoService=buildSprint9ADemo();
export const sprint9ACompleteProject=sprint9ADemoService.getProject("inquiry_synthetic_41236_complete");
export const sprint9ACompleteReport=sprint9ADemoService.getReport(sprint9ACompleteProject.id,true);
