import type { AuditEvent } from "../research-license/engine";
import { calculateAnalysis } from "./analysis";
import { buildInquiryReport } from "./report";
import type { AnalysisMethod, CERStatement, ChartSpecification, CleaningAction, DatasetColumn, DatasetRow, InquiryActor, InquiryDataset, InquiryEvidenceLink, InquiryProject, InquiryRecommendation, InquiryReview, InquiryState, OneHealthSystemMap, ResearchDesign } from "./types";
import { validateCER, validateProjectFoundation, validateResearchDesign } from "./validation";

const clone = <T>(value: T): T => structuredClone(value);
function audit(actor: InquiryActor, entityType: string, entityId: string, action: string, now: Date, extra: Partial<AuditEvent> = {}): AuditEvent { return { actorId: actor.id, actorRole: actor.role, entityType, entityId, action, timestamp: now, ...extra }; }

export class InquiryService {
  state: InquiryState;
  constructor(initial?: Partial<InquiryState>) { this.state = { projects: initial?.projects ?? new Map(), evidenceLinks: initial?.evidenceLinks ?? [], designs: initial?.designs ?? [], datasets: initial?.datasets ?? [], analyses: initial?.analyses ?? [], cerStatements: initial?.cerStatements ?? [], systemMaps: initial?.systemMaps ?? [], recommendations: initial?.recommendations ?? [], reviews: initial?.reviews ?? [], competencyEvidence: initial?.competencyEvidence ?? [], auditEvents: initial?.auditEvents ?? [] }; }
  private record(events: AuditEvent[]) { this.state.auditEvents.push(...events); return events; }
  getProject(id: string) { const project=this.state.projects.get(id); if(!project) throw new Error("Inquiry project not found."); return project; }
  private editable(actor: InquiryActor, id: string) { const project=this.getProject(id); if(actor.role!=="student"||actor.id!==project.ownerStudentId) throw new Error("Only the owning student can edit this inquiry."); if(!["draft","question_review","design_review","data_collection","analysis"].includes(project.status)) throw new Error("Submitted inquiry versions are immutable."); return project; }
  private teacherAuthorized(actor: InquiryActor, project: InquiryProject) { if(actor.role==="admin") return; if(actor.role!=="teacher"||actor.id!==project.supervisingTeacherId) throw new Error("Teacher is not authorized for this inquiry."); if(project.courseId&&!actor.authorizedCourseIds?.includes(project.courseId)) throw new Error("Teacher course scope is not authorized."); }
  private shelterAuthorized(actor: InquiryActor, project: InquiryProject) { if(actor.role==="admin") return; if(actor.role!=="shelter_staff"||!project.shelterId||!actor.authorizedShelterIds?.includes(project.shelterId)) throw new Error("Shelter review is not authorized."); }

  createProject(actor: InquiryActor, input: Omit<InquiryProject,"id"|"parentProjectId"|"revisionNumber"|"status"|"createdAt"|"updatedAt"|"submittedAt"|"teacherApprovedAt"|"shelterConfirmedAt"|"publishedAt"|"rowVersion"|"submittedSnapshot"> & {id?:string}, now: Date) {
    if(actor.role!=="student"&&actor.role!=="admin") throw new Error("Only a student or admin can create an inquiry project.");
    if(actor.role==="student"&&input.ownerStudentId!==actor.id) throw new Error("Student can create only their own inquiry.");
    const project: InquiryProject={...input,id:input.id??`inquiry_${now.getTime()}`,revisionNumber:1,status:"draft",createdAt:now,updatedAt:now,rowVersion:0};
    this.state.projects.set(project.id,project); const events=this.record([audit(actor,"inquiry_project",project.id,"inquiry_project_created",now,{newState:project as unknown as Record<string,unknown>})]); return {project,auditEvents:events};
  }
  updateProject(actor: InquiryActor,id:string,patch:Partial<Pick<InquiryProject,"title"|"oneHealthDimensions"|"oneHealthConnection"|"learningStandardIds"|"researchQuestion"|"background"|"hypothesis"|"independentVariable"|"dependentVariable"|"controlledVariables"|"evidenceScope"|"reflection">>,expectedRowVersion:number,now:Date){const project=this.editable(actor,id);if(project.rowVersion!==expectedRowVersion)throw new Error("Inquiry row version conflict.");const updated={...project,...patch,rowVersion:project.rowVersion+1,updatedAt:now};this.state.projects.set(id,updated);const events=this.record([audit(actor,"inquiry_project",id,"inquiry_project_updated",now,{previousState:project as unknown as Record<string,unknown>,newState:updated as unknown as Record<string,unknown>})]);return{project:updated,auditEvents:events};}
  linkEvidence(actor:InquiryActor,projectId:string,input:Omit<InquiryEvidenceLink,"id"|"projectId"|"includedAt"|"includedBy">,now:Date){this.editable(actor,projectId);if(input.verificationState==="UNVERIFIED"&&input.evidenceType==="government_dataset_snapshot") throw new Error("Unverified external records cannot be linked as approved evidence.");const link={...input,id:`evidence_${projectId}_${this.state.evidenceLinks.length+1}`,projectId,includedAt:now,includedBy:actor.id};this.state.evidenceLinks.push(link);const events=this.record([audit(actor,"inquiry_evidence_link",link.id,"inquiry_evidence_linked",now,{newState:link})]);return{link,auditEvents:events};}
  saveDesign(actor:InquiryActor,projectId:string,input:Omit<ResearchDesign,"id"|"projectId"|"flags"|"version"|"createdAt">,now:Date){const project=this.editable(actor,projectId);const prior=this.state.designs.filter(d=>d.projectId===projectId);const base={...input,id:`design_${projectId}_v${prior.length+1}`,projectId,version:prior.length+1,createdAt:now};const design={...base,flags:validateResearchDesign(project,base,this.state.evidenceLinks.filter(e=>e.projectId===projectId))};this.state.designs.push(design);this.state.projects.set(projectId,{...project,status:"design_review",updatedAt:now});const events=this.record([audit(actor,"inquiry_research_design",design.id,"research_design_version_created",now,{newState:design as unknown as Record<string,unknown>})]);return{design,auditEvents:events};}
  createDataset(actor:InquiryActor,projectId:string,input:{name:string;columns:DatasetColumn[];rows:DatasetRow[];sourceProvenance:string[];syntheticDemo:boolean;id?:string},now:Date){this.editable(actor,projectId);const id=input.id??`dataset_${projectId}_${this.state.datasets.length+1}`;const original={id:`${id}_v1_original`,datasetId:id,version:1,kind:"original" as const,rows:clone(input.rows),sourceProvenance:[...input.sourceProvenance],cleaningActions:[],immutable:true as const,createdAt:now};const dataset:InquiryDataset={id,projectId,name:input.name,columns:input.columns,versions:[original],syntheticDemo:input.syntheticDemo,createdAt:now};this.state.datasets.push(dataset);const events=this.record([audit(actor,"inquiry_dataset",id,"inquiry_dataset_created",now,{changes:{rows:input.rows.length,sourceProvenance:input.sourceProvenance}})]);return{dataset,auditEvents:events};}
  transformDataset(actor:InquiryActor,projectId:string,datasetId:string,input:Omit<CleaningAction,"id"|"createdAt"|"actorId">,now:Date){this.editable(actor,projectId);const dataset=this.state.datasets.find(d=>d.id===datasetId&&d.projectId===projectId);if(!dataset)throw new Error("Inquiry dataset not found.");if(["correct_invalid_code","exclude_with_reason"].includes(input.action)&&!input.reason?.trim())throw new Error("This cleaning action requires a reason.");const source=dataset.versions.at(-1)!;const rows=clone(source.rows);if(input.action==="remove_duplicate"){const seen=new Set<string>();for(let i=rows.length-1;i>=0;i--){const key=JSON.stringify(rows[i]);if(seen.has(key))rows.splice(i,1);else seen.add(key);}}else if(input.action==="correct_invalid_code"&&input.column&&input.rowIndex!==undefined)rows[input.rowIndex][input.column]=input.toValue??null;else if(input.action==="mark_missing"&&input.column&&input.rowIndex!==undefined)rows[input.rowIndex][input.column]=null;else if(input.action==="exclude_with_reason"&&input.rowIndex!==undefined)rows.splice(input.rowIndex,1);else if(["standardize_category","standardize_unit"].includes(input.action)&&input.column)for(const row of rows)if(row[input.column]===input.fromValue)row[input.column]=input.toValue??null;else if(input.action==="create_derived_field"&&input.column){if(!input.formulaDescription?.trim())throw new Error("Derived field requires a formula description.");for(const row of rows)row[input.column]=input.toValue??null;}else if(input.action==="merge_approved_datasets"){if(!input.reason?.trim())throw new Error("Dataset merge requires approved-source reason.");}
    const action={...input,id:`clean_${datasetId}_${source.version}`,createdAt:now,actorId:actor.id};const version={id:`${datasetId}_v${source.version+1}_cleaned`,datasetId,version:source.version+1,kind:"cleaned" as const,rows,sourceProvenance:[...source.sourceProvenance],cleaningActions:[...source.cleaningActions,action],immutable:true as const,createdAt:now};dataset.versions.push(version);const events=this.record([audit(actor,"inquiry_dataset_version",version.id,"inquiry_data_transformed",now,{reason:input.reason,changes:{action:input.action,sourceVersion:source.id,newVersion:version.id}})]);return{version,auditEvents:events};}
  addAnalysis(actor:InquiryActor,projectId:string,input:{datasetVersionId:string;method:AnalysisMethod;variables:string[];filteredPopulation:string;interpretationNote:string;limitationNote:string;chart:Omit<ChartSpecification,"sampleSize"|"source">&{source?:string;sampleSize?:number}},now:Date){const project=this.editable(actor,projectId);const version=this.state.datasets.flatMap(d=>d.versions).find(v=>v.id===input.datasetVersionId);if(!version)throw new Error("Dataset version not found.");const result=calculateAnalysis({id:`analysis_${projectId}_${this.state.analyses.length+1}`,projectId,dataset:version,...input,generatedAt:now});this.state.analyses.push(result);this.state.projects.set(projectId,{...project,status:"analysis",updatedAt:now});const events=this.record([audit(actor,"inquiry_analysis_result",result.id,"inquiry_analysis_calculated",now,{changes:{method:result.method,numerator:result.numerator,denominator:result.denominator,calculationVersion:result.calculationVersion}})]);return{result,auditEvents:events};}
  addCER(actor:InquiryActor,projectId:string,input:Omit<CERStatement,"id"|"projectId"|"flags"|"version"|"createdAt">,now:Date){this.editable(actor,projectId);const links=this.state.evidenceLinks.filter(e=>e.projectId===projectId);const correlational=this.state.analyses.some(a=>a.projectId===projectId&&a.method==="simple_correlation");const statement={...input,id:`cer_${projectId}_${this.state.cerStatements.length+1}`,projectId,flags:validateCER(input,links,correlational),version:this.state.cerStatements.filter(c=>c.projectId===projectId).length+1,createdAt:now};this.state.cerStatements.push(statement);const events=this.record([audit(actor,"cer_statement",statement.id,"cer_version_created",now,{newState:statement as unknown as Record<string,unknown>})]);return{statement,auditEvents:events};}
  saveSystemMap(actor:InquiryActor,projectId:string,input:Omit<OneHealthSystemMap,"id"|"projectId"|"version"|"createdAt">,now:Date){this.editable(actor,projectId);for(const edge of input.edges)if(edge.evidenceLinkIds.length===0)throw new Error("System-map edges require evidence.");const map={...input,id:`system_map_${projectId}_v${this.state.systemMaps.filter(m=>m.projectId===projectId).length+1}`,projectId,version:this.state.systemMaps.filter(m=>m.projectId===projectId).length+1,createdAt:now};this.state.systemMaps.push(map);const events=this.record([audit(actor,"one_health_system_map",map.id,"one_health_system_map_revised",now,{changes:{nodes:map.nodes.length,edges:map.edges.length}})]);return{map,auditEvents:events};}
  addRecommendation(actor:InquiryActor,projectId:string,input:Omit<InquiryRecommendation,"id"|"projectId"|"createdAt">,now:Date){this.editable(actor,projectId);if(input.supportingEvidence.length===0)throw new Error("Recommendation requires supporting evidence.");const recommendation={...input,id:`recommendation_${projectId}_${this.state.recommendations.length+1}`,projectId,createdAt:now};this.state.recommendations.push(recommendation);const events=this.record([audit(actor,"inquiry_recommendation",recommendation.id,"inquiry_recommendation_proposed",now,{newState:recommendation as unknown as Record<string,unknown>})]);return{recommendation,auditEvents:events};}
  submit(actor:InquiryActor,projectId:string,now:Date){const project=this.editable(actor,projectId);const links=this.state.evidenceLinks.filter(e=>e.projectId===projectId);const flags=validateProjectFoundation(project,links);if(flags.some(f=>f.severity==="error"))throw new Error(flags.map(f=>f.message).join(" "));if(!this.state.designs.some(d=>d.projectId===projectId)||!this.state.analyses.some(a=>a.projectId===projectId)||!this.state.cerStatements.some(c=>c.projectId===projectId)||!this.state.systemMaps.some(m=>m.projectId===projectId)||!this.state.recommendations.some(r=>r.projectId===projectId))throw new Error("Complete design, analysis, CER, system map, and recommendation before submission.");const updated={...project,status:"submitted" as const,submittedAt:now,updatedAt:now,submittedSnapshot:clone(project) as unknown as Record<string,unknown>};this.state.projects.set(projectId,updated);const events=this.record([audit(actor,"inquiry_project",projectId,"inquiry_project_submitted",now,{fromStatus:project.status,toStatus:"submitted"})]);return{project:updated,auditEvents:events};}
  teacherReview(actor:InquiryActor,projectId:string,decision:"approve"|"request_revision"|"reject",reason:string|undefined,rubric:Record<string,number>,now:Date){const project=this.getProject(projectId);this.teacherAuthorized(actor,project);if(project.status!=="submitted")throw new Error("Teacher reviews the immutable submitted version.");if(decision!=="approve"&&!reason?.trim())throw new Error("Revision or rejection requires a reason.");const requiresShelter=this.requiresShelterReview(projectId);const status:InquiryProject["status"]=decision==="approve"?(requiresShelter?"shelter_review":"teacher_approved"):decision==="request_revision"?"teacher_revision":"teacher_rejected";const review:InquiryReview={id:`review_teacher_${projectId}_${project.revisionNumber}`,projectId,reviewerId:actor.id,reviewerRole:actor.role==="admin"?"admin":"teacher",stage:"final",decision,reason,rubric,projectRevision:project.revisionNumber,createdAt:now};this.state.reviews.push(review);const updated:InquiryProject={...project,status,teacherApprovedAt:decision==="approve"?now:undefined,updatedAt:now};this.state.projects.set(projectId,updated);this.recordCompetencies(projectId,rubric,now);const recommendationEvents=this.reviewRecommendations(actor,projectId,decision==="approve"?"teacher_approved":decision==="request_revision"?"teacher_revision":"rejected",reason,now);const events=this.record([audit(actor,"inquiry_review",review.id,`inquiry_teacher_${decision}`,now,{fromStatus:project.status,toStatus:status,reason}),...recommendationEvents]);return{project:updated,review,auditEvents:events};}
  shelterReview(actor:InquiryActor,projectId:string,decision:"confirm"|"request_revision"|"reject",reason:string|undefined,now:Date){const project=this.getProject(projectId);this.shelterAuthorized(actor,project);if(project.status!=="shelter_review")throw new Error("Shelter review requires teacher approval.");if(decision!=="confirm"&&!reason?.trim())throw new Error("Revision or rejection requires a reason.");const status:InquiryProject["status"]=decision==="confirm"?"shelter_confirmed":decision==="request_revision"?"shelter_revision":"shelter_rejected";const review:InquiryReview={id:`review_shelter_${projectId}_${project.revisionNumber}`,projectId,reviewerId:actor.id,reviewerRole:actor.role==="admin"?"admin":"shelter_staff",stage:"recommendation",decision,reason,rubric:{},projectRevision:project.revisionNumber,createdAt:now};this.state.reviews.push(review);const updated:InquiryProject={...project,status,shelterConfirmedAt:decision==="confirm"?now:undefined,updatedAt:now};this.state.projects.set(projectId,updated);const recommendationEvents=this.reviewRecommendations(actor,projectId,decision==="confirm"?"shelter_confirmed":decision==="request_revision"?"shelter_revision":"rejected",reason,now,true);const events=this.record([audit(actor,"inquiry_review",review.id,`inquiry_shelter_${decision}`,now,{fromStatus:project.status,toStatus:status,reason}),...recommendationEvents]);return{project:updated,review,auditEvents:events};}
  finalize(actor:InquiryActor,projectId:string,now:Date){const project=this.getProject(projectId);this.teacherAuthorized(actor,project);const required=this.requiresShelterReview(projectId);if(!project.teacherApprovedAt)throw new Error("Teacher approval is required before finalization.");if(required&&!project.shelterConfirmedAt)throw new Error("Shelter confirmation is required for this inquiry.");if(!["teacher_approved","shelter_confirmed"].includes(project.status))throw new Error("Inquiry is not ready for finalization.");const cers=this.state.cerStatements.filter(c=>c.projectId===projectId);const links=this.state.evidenceLinks.filter(e=>e.projectId===projectId);if(cers.some(c=>validateCER(c,links,this.state.analyses.some(a=>a.projectId===projectId&&a.method==="simple_correlation")).some(f=>f.severity==="error")))throw new Error("Final claims require approved traceable evidence.");const updated={...project,status:"final" as const,publishedAt:now,updatedAt:now,dataClassification:"public_approved" as const};this.state.projects.set(projectId,updated);const events=this.record([audit(actor,"inquiry_project",projectId,"inquiry_final_approved",now,{fromStatus:project.status,toStatus:"final"})]);return{project:updated,auditEvents:events};}
  createRevision(actor:InquiryActor,projectId:string,now:Date){const parent=this.getProject(projectId);if(actor.role!=="student"||actor.id!==parent.ownerStudentId)throw new Error("Only the owning student can revise.");if(!["teacher_revision","shelter_revision","teacher_rejected","shelter_rejected"].includes(parent.status))throw new Error("Revision requires a review decision.");const child={...clone(parent),id:`${parent.id}_r${parent.revisionNumber+1}`,parentProjectId:parent.id,revisionNumber:parent.revisionNumber+1,status:"draft" as const,createdAt:now,updatedAt:now,submittedAt:undefined,teacherApprovedAt:undefined,shelterConfirmedAt:undefined,publishedAt:undefined,rowVersion:0,submittedSnapshot:undefined};this.state.projects.set(child.id,child);const events=this.record([audit(actor,"inquiry_project",child.id,"inquiry_revision_created",now,{previousState:{parentProjectId:parent.id,parentStatus:parent.status},newState:{revisionNumber:child.revisionNumber,status:"draft"}})]);return{project:child,auditEvents:events};}
  requiresShelterReview(projectId:string){const project=this.getProject(projectId);return Boolean(project.shelterId)||this.state.evidenceLinks.some(e=>e.projectId===projectId&&["observation_session","published_dog_evidence"].includes(e.evidenceType))||this.state.recommendations.some(r=>r.projectId===projectId&&r.targetActor==="shelter");}
  getReport(projectId:string,publicView:boolean){const project=this.getProject(projectId);if(publicView&&project.status!=="final")throw new Error("Only final inquiry reports are public.");return buildInquiryReport({project,evidence:this.state.evidenceLinks.filter(e=>e.projectId===projectId),design:this.state.designs.filter(d=>d.projectId===projectId).at(-1),datasets:this.state.datasets.filter(d=>d.projectId===projectId),analyses:this.state.analyses.filter(a=>a.projectId===projectId),cer:this.state.cerStatements.filter(c=>c.projectId===projectId),systemMap:this.state.systemMaps.filter(m=>m.projectId===projectId).at(-1),recommendations:this.state.recommendations.filter(r=>r.projectId===projectId),publicView});}
  private recordCompetencies(projectId:string,rubric:Record<string,number>,now:Date){const competencies=["scientific_observation","research_question_formation","research_design","data_collection","data_cleaning","data_interpretation","evidence_based_reasoning","one_health_understanding","scientific_communication","ethical_reasoning"] as const;for(const competency of competencies)this.state.competencyEvidence.push({id:`competency_${projectId}_${competency}`,projectId,competency,evidenceEntityIds:[projectId],teacherScore:rubric[competency],version:1,syntheticDemo:this.getProject(projectId).syntheticDemo,createdAt:now});}
  private reviewRecommendations(actor:InquiryActor,projectId:string,status:InquiryRecommendation["status"],reason:string|undefined,now:Date,shelterOnly=false){const events:AuditEvent[]=[];for(const recommendation of this.state.recommendations.filter(item=>item.projectId===projectId&&(!shelterOnly||item.targetActor==="shelter"))){const previous=recommendation.status;recommendation.status=status;events.push(audit(actor,"inquiry_recommendation",recommendation.id,"inquiry_recommendation_reviewed",now,{fromStatus:previous,toStatus:status,reason}));}return events;}
}
